### ISSUE TITLE
Implicit output within CF tags

### ISSUE THREAD

**Issue by KamasamaK** [jcberquist/sublimetext-cfml#102]
Some CFML tags such as `cfmail` implicitly have output enabled and the syntax scopes should reflect this as it does within `cfoutput` and `cfquery`. I'm not sure what other tags are missing this, so for now this is just for `cfmail`.

**Comment by jcberquist** [comment]
Thanks for the report - in order to keep the syntax file from growing massively in size I am reusing contexts.  As long as tags (`cfoutput` and `cfmail`) are nested validly, that should hopefully not cause any issues.
