### ISSUE TITLE
The `multiline.element_count` property is not being honored for the 'function_call' delimited scope

### ISSUE THREAD

**Issue by micahknox** [jcberquist/sublimetext-cfml#104]
Regardless of what value I provide for the `multiline.element_count` property of the 'function_call' delimited scope in my user settings for the CFML Formatter, it always breaks when there are 2 or more arguments passed into the function call. It seems like this property should indicate a break if there are a certain number of arguments being passed into the method.

**Comment by micahknox** [comment]
Please disregard. I discovered that the `singleline_max_col` overrides the `element_count` so increasing the maximum column size fixed my issue.

**Comment by jcberquist** [comment]
Sounds like this is sorted out.
