### ISSUE TITLE
Adding forward slash inside existing cfml tag causes incorrect closing tag insert

### ISSUE THREAD

**Issue by redtopia** [jcberquist/sublimetext-cfml#108]
Sometimes when writing in tag mode, I copy/paste a start cfml tag to the place where I want to end it, then I add a forward slash to the tag. When I do this, sometimes a different end tag is added when I enter the forward slash.

In this example, I've already pasted the `<cfoutput>` tag to where I want to put it, and then I am adding the forward slash. As you can see, it adds the `</div>` instead of just letting me add the forward slash.

![erqczdfsq0](https://user-images.githubusercontent.com/812777/36173685-11602b7e-10c7-11e8-8901-47f246866602.gif)

**Comment by jcberquist** [comment]
Thanks for the report. I think the quickest solution would be to not fire the close tag command if the characters after the cursor position look like `xxxxx>`. Does that sound like it would work for you?

**Comment by redtopia** [comment]
I think it could be that simple!
