### ISSUE TITLE
<cfmailparam /> tag support

### ISSUE THREAD

**Issue by WebVeteran** [jcberquist/sublimetext-cfml#109]
Please add the CFMAILPARAM tag. When I use that tag, things get ugly.
![screen shot 2018-02-26 at 9 20 52 pm](https://user-images.githubusercontent.com/40175/36707140-082431da-1b3b-11e8-8a52-27dd7acd78e3.png)
And then down the link... even uglier still.
![screen shot 2018-02-26 at 9 22 16 pm](https://user-images.githubusercontent.com/40175/36707157-1eb5e5e2-1b3b-11e8-9966-71dd8eab8ba1.png)
When I remove the cfmailparam tag, all highlighting goes back to normal.
![screen shot 2018-02-26 at 9 22 54 pm](https://user-images.githubusercontent.com/40175/36707176-3251e7ea-1b3b-11e8-80e8-c5d9a74aeba9.png)

**Comment by jcberquist** [comment]
This should be fixed now. Sorry about that.
