### ISSUE TITLE
Error trying to parse file: Unexpected character, expected a comma or closing bracket

### ISSUE THREAD

**Issue by ivanionut** [jcberquist/sublimetext-cfml#11]
Hi,
now, when I open sublime text, I get the following error:

`Error trying to parse file: Unexpected character, expected a comma or closing bracket in Packages/CFML/keymaps/Default (OSX).sublime-keymap:70:3`

**Comment by jcberquist** [comment]
Sorry about that! It is fixed now, though it may take Package Control a little while to pick up the new release.
