### ISSUE TITLE
cfml_format removes SQL indentation in string

### ISSUE THREAD

**Issue by l8nites** [jcberquist/sublimetext-cfml#117]
Strongly prefer to leave indentation in strings alone.

**Comment by l8nites** [comment]
![sublime_text_2018-05-24_18-40-08](https://user-images.githubusercontent.com/7915110/40518818-04b3244e-5f82-11e8-9e93-29b91ee8df7d.png)
is formatted as 
![image](https://user-images.githubusercontent.com/7915110/40518826-0d39e490-5f82-11e8-8ef7-c70325427501.png)

**Comment by jcberquist** [comment]
Yeah, good call, thanks for the nudge. I also need to work on multiline comments and switch blocks.
