### ISSUE TITLE
Plugin Conflict

### ISSUE THREAD

**Issue by PwrSrg** [jcberquist/sublimetext-cfml#120]
The plugin has a direct conflict with "Java​Script​Next - ES6 Syntax" which causes the following error:

![image](https://user-images.githubusercontent.com/711603/43540935-a7492842-958e-11e8-81fd-000076cf591b.png)

https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax

**Comment by jcberquist** [comment]
You can see from some of the previous issues here that this is a recurring issue with some third party JavaScript and CSS syntaxes: #113, #114, #118 - If you visit the repositories for the JavaScriptNext syntax or the CSS3 syntax you will see in their issues that it is an ongoing problem for them.

I am going to close this issue as there isn't really anything I can do to "fix" this.

**Comment by PwrSrg** [comment]
BTW, thanks for the good work!
