### ISSUE TITLE
Autocomplete tag should not happen when forward slash is added to beginning (to close it)

### ISSUE THREAD

**Issue by redtopia** [jcberquist/sublimetext-cfml#121]
When adding a forward slash to the beginning of a tag (in order to close it), autocomplete messes things up by auto-completing the previous tag (see screenshot).

![capture](https://user-images.githubusercontent.com/812777/44480669-0f7f9e00-a601-11e8-81a2-2458534ce009.gif)

**Comment by jcberquist** [comment]
Thanks! It looks like the regex test I wrote for #108 isn't quite right and doesn't handle cases where there is more text on the current line after the tag.
