### ISSUE TITLE
Code completions stopped working

### ISSUE THREAD

**Issue by rossmd** [jcberquist/sublimetext-cfml#125]
Sublime Text recently updated and it seems like CFML code completions have stopped working.  I see the following in the ST console:

`Nodejs Plugin - INFO - 2019-02-01T11:29:35.341660 => Running `node_builddocs` to generate Node.js completions
CFML: indexing components in project 'C:/Users/mross/Sublime Projects/regaction.sublime-project'
Traceback (most recent call last):
  File "C:\Users\mross\AppData\Roaming\Sublime Text 3\Installed Packages\CFML.sublime-package\src/component_index/component_index.py", line 88, in index_project
AttributeError: 'NoneType' object has no attribute 'parse_directory'`

I am using ST 3 Dev Channel Build 3189

-Mark

**Comment by jcberquist** [comment]
Thank you! I couldn't get to ST to investigate fully right away, but I saw the release notes for 3189 and thought there was going to be trouble.
