### ISSUE TITLE
Empty script block comment never closes

### ISSUE THREAD

**Issue by je0** [jcberquist/sublimetext-cfml#127]
The following code shows everything as grey after the **cfscript** tag (note the comment block with nothing inside):
![cfml-script-comment](https://user-images.githubusercontent.com/11130647/60115333-4b145880-973b-11e9-93ba-29784fdafea2.jpg)

But the dump is still executed (Lucee 5.2.8.50).

Not sure if this is a bug with Lucee, this package, or something else, but hopefully you can point me in the right direction.

Edit: ST 3.2.1 build 3207, CFML v0.28.0

**Comment by jcberquist** [comment]
Thanks, this is definitely a syntax highlighting bug in the CFML plugin.

**Comment by jcberquist** [comment]
I have released v0.28.1 that contains a fix for this. It often takes a little while for Package Control to pick up the new release.
