### ISSUE TITLE
Syntax highlighting breaks after inline style attribute in tag

### ISSUE THREAD

**Issue by alxmckny** [jcberquist/sublimetext-cfml#128]
Hi @jcberquist,
The CFML syntax highlighting in ST3 seems to be breaking after an inline `style` attribute in any standard HTML tag in a .cfm document:

![Screen Shot 2019-07-08 at 3 33 15 PM](https://user-images.githubusercontent.com/2211973/60837772-08b93580-a197-11e9-90c4-1396c28213dc.png)

If I change the attribute to `data-style`, the issue disappears:

![Screen Shot 2019-07-08 at 3 34 35 PM](https://user-images.githubusercontent.com/2211973/60837867-53d34880-a197-11e9-9c66-d68abcdd90b2.png)

If I switch the syntax in ST3 to "HTML" the issue disappears as well:

![Screen Shot 2019-07-08 at 3 33 49 PM](https://user-images.githubusercontent.com/2211973/60837925-7cf3d900-a197-11e9-80b5-8e055a56fd72.png)

I have tried disabling any associated 3rd party packages just in case, but it doesn't seem to help the issue. Can you replicate this on your end, or have any ideas as to what may cause this?

**Comment by jcberquist** [comment]
I can't reproduce this on my end. I do see in your 3rd image, where you selected `HTML` as the syntax, that the CSS in the style attribute is not highlighted as CSS. That suggests to me that something non-standard is going on, since with the default packages that should be highlighted. Did you add `CSS` to your ignored packages list in your preferences?

**Comment by alxmckny** [comment]
I did have `CSS` in my ignored packages. I tried removing that and the issue is still there for me. Any other ideas on what to try?

**Comment by jcberquist** [comment]
Can you confirm that you have `CSS` as a syntax choice in your syntax menu? Do you have a third party CSS syntax installed?

**Comment by alxmckny** [comment]
Yes. I have `CSS` and `CSS3` in the syntax menu:

![Screen Shot 2019-07-08 at 5 42 32 PM](https://user-images.githubusercontent.com/2211973/60844634-eb409780-a1a7-11e9-9101-5751ee07f8d0.png)

**Comment by jcberquist** [comment]
Could you try disabling `CSS3`?

**Comment by alxmckny** [comment]
Disabling `CSS3` worked! Thank you for helping troubleshoot this issue.

**Comment by jcberquist** [comment]
Glad to hear it. There has been trouble in the past as well with getting this package to work specifically with CSS3.
