### ISSUE TITLE
Make separate ColdFusion formatter, editor agnostic

### ISSUE THREAD

**Issue by Alexey-T** [jcberquist/sublimetext-cfml#129]
Currently you have CFML formatter which requires module "sublime". so I cannot use it in another Python project. Can you please separate it (make editor independent, and make wrapper for Sublime plugin)?

API can be like:

    def format_text(text, options={}):

where "options" is dict with several keys (if you need it).

**Comment by jcberquist** [comment]
The formatter actually depends on the internal ST Python API in order to do its work, so I don't think I can separate it out, sorry!

**Comment by KamasamaK** [comment]
@Alexey-T This may not be what you're looking for, but [jcberquist/commandbox-cfformat](https://github.com/jcberquist/commandbox-cfformat) is separate and editor agnostic. You would just have to use it via CLI instead of Python API.

**Comment by Alexey-T** [comment]
CLI... now quite ok for my python script for CudaText.
