### ISSUE TITLE
Custom Tag Attribute Indexing Finds Chained Methods

### ISSUE THREAD

**Issue by michaelalandawson** [jcberquist/sublimetext-cfml#132]
Sublime Text 3.2.2, Build 3211, most-recent CFML package

I added "custom_tag_folders" to a project settings file.  I am now able to see completions for custom tags in that folder, as well as attributes in those custom tags.  I regret not adding this earlier as it is a wonderful time saver.

I noticed the indexer, finds elements other than attributes-based variables.

`if (attributes.keyExists("pageTitle") and attributes.pageTitle.trim().len()) {`

The attributes indexing code adds "keyexists" to the completions list for attributes.  This is a chained method and not a variable.

Thank you for an excellent ColdFusion package!

**Comment by jcberquist** [comment]
I pushed an update in `st3-v0.29.1` that should fix this.
