### ISSUE TITLE
SQL Syntax Highlighting does not Recognize SQL Server TOP Keyword

### ISSUE THREAD

**Issue by michaelalandawson** [jcberquist/sublimetext-cfml#133]
There are a few instances where the TOP keyword is not recognized correctly and this causes the SQL syntax highlighting to revert to default text.  I hope these examples can help improve the syntax highlighting.

Here is a basic query that is displayed correctly.

![sql1](https://user-images.githubusercontent.com/39276677/92633323-3a94c300-f298-11ea-8d7e-b2329b851d61.png)

If I add the "top" keyword, the syntax doesn't change, but this is not a valid SQL statement.

![sql2a](https://user-images.githubusercontent.com/39276677/92633401-5730fb00-f298-11ea-9cee-b573c806a228.png)

If I bring up a column to the same line as the "top" keyword, the syntax highlighting fails.  This is still invalid SQL, but is basically the same logic as the previous invalid example that uses syntax highlighting.

![sql2b](https://user-images.githubusercontent.com/39276677/92633529-82b3e580-f298-11ea-8b75-fd35ee4a5f5a.png)

Here is an example of valid SQL using "select top n".  (This is no longer recommended by Microsoft, but is still supported.)

![sql3](https://user-images.githubusercontent.com/39276677/92633567-91020180-f298-11ea-91f1-692a1c902168.png)

This is valid SQL using Microsoft's recommendation of "top(n)".  Syntax highlighting doesn't recognize this.

![sql4](https://user-images.githubusercontent.com/39276677/92633705-c4449080-f298-11ea-96bf-a9237816cce0.png)

This is an example of using a SQL variable in the "top()" keyword.

![sql5a](https://user-images.githubusercontent.com/39276677/92633838-01108780-f299-11ea-941b-582a0ebf849b.png)

Finally, an example of using a parameter in the "top()" keyword.

![sql5b](https://user-images.githubusercontent.com/39276677/92633902-15ed1b00-f299-11ea-9060-5bd0a83b446a.png)

**Comment by jcberquist** [comment]
Thanks for reporting, I have tried to improve the `top` matching in `st3-v0.29.1`.

**Comment by michaelalandawson** [comment]
Thank you very much.  It looks great.  I did find another instance to tweak the highlighting regarding a query param and the SQL "limit" keyword.

This example highlights ":limit" as an SQL keyword when, in this case, is only a query parameter.  My use of ":limit" as a query parameter is valid.  Perhaps the matching could look for a leading colon, and if found, consider it a parameter.

![sql1](https://user-images.githubusercontent.com/39276677/92656782-43e25780-f2b9-11ea-90c7-217fdad85956.png)

If I rename the query parameter, highlighting works, as expected.

![sql2](https://user-images.githubusercontent.com/39276677/92656789-46dd4800-f2b9-11ea-872a-38dc45a00fdc.png)

If you will allow me to go one step further, the following can be added to the "top" keyword:  "percent" and "percent with ties"

![sql3](https://user-images.githubusercontent.com/39276677/92657410-645ee180-f2ba-11ea-86ed-3555a64a154e.png)

Again, thank you for making this package.

**Comment by jcberquist** [comment]
I am glad that the original issue has been resolved.

In the first screenshots, the issue was that the SQL syntax was not being used at all, whereas in these latest ones the issue has to do with the SQL syntax itself. The SQL syntax comes from Sublime Text, it is not part of this package. It is a generic syntax, so SQL Server specific syntax is unlikely to be supported well.

As far as recognizing CFML parameters (e.g. `:param`), that might be possible down the road, but it would probably involve creating a custom syntax. So I don't think I can address it right now.

**Comment by michaelalandawson** [comment]
Understood.  Thank you for looking at this.
