### ISSUE TITLE
Sublime 4 compatibility

### ISSUE THREAD

**Issue by beauars** [jcberquist/sublimetext-cfml#138]
Just downloaded sublime 4 and it said this CFML plugin isn't compatible.  I uninstalled and reinstalled it too and it doesn't appear to be working.  Oh no!  I hope you guys will update this soon.  Thanks!

**Comment by jcberquist** [comment]
I have been using this with Sublime Text 4 for quite some time, and made some updates a while ago to support ST4. If you visit <https://packagecontrol.io/packages/CFML> you will see that there are two latest versions listed: `0.30.3` and `0.29.3`. The `0.30.3` version is the ST4 version. Can you confirm that is the version you are on? I also tried a new portable install of ST4 and installed the CFML plugin, and it seemed to work just fine. So I am not sure what is going on for you. Could you say more about the issues you are seeing?

**Comment by beauars** [comment]
Thanks John!  Yes, I had 0.30.3. I closed sublime and opened it again
(doesn't seem to restart because it's so quick and keeps the same files
open) and there was no color coding for cfml.

So after getting your email I uninstalled and reinstalled your CFML plugin
using package control.  Same result.  But you know what?  If you close a
CFM file and open it again, it shows the color coding! I think I'm good to
go.  Thank you very much!  Also, if you're interested, I got this message
after installing:

Package Control Messages
========================

CFML
----

  CFML (ColdFusion/Lucee) package for Sublime Text 3
  https://github.com/jcberquist/sublimetext-cfml

  Thank you for installing this package. Please see the readme at the GitHub
  repository for more information about the features of this package.

  The GitHub repository is also the place to raise any issues you encounter.

  *IMPORTANT: Sublime Text 3 must be restarted for this package to function
properly.*

**Comment by jcberquist** [comment]
Thanks, glad to hear it is working. When you update a plugin like that, I have found that any currently open files using that syntax do need to be closed and re-opened for the correct syntax highlighting to take effect. And thanks for pointing out the message, I noticed that too when I was testing installing the CFML package fresh.
