### ISSUE TITLE
ST4 Build 4181 Apparent recursion within a with_prototype action

### ISSUE THREAD

**Issue by ivanionut** [jcberquist/sublimetext-cfml#149]
hello, in the latest version of SublimeText 4 build 4181, the following error appears during start-up:

```
Error loading syntax file "Packages/CFML/syntaxes/cfml.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit
```

**Comment by jcberquist** [comment]
It looks like the latest updates to the JavaScript syntax that ships with ST have caused this issue - it looks like it started with this PR: https://github.com/sublimehq/Packages/pull/4019. For now, if you want to stay on the dev builds, you will need to checkout the sublimehq/Packages repo at a commit prior to the above merge, and manually add the `JavaScript` package to your Packages folder to override the updates.

Updating the CFML syntax that ships with this package will take some time, as it needs to be updated to take advantage of features added more recently to the ST syntax engine.

**Comment by jcberquist** [comment]
With `v0.31.0` syntax highlighting should work again in the latest Sublime Text stable version 4186. However, if you have overridden the default JavaScript syntax file `Packages/JavaScript/JavaScript.sublime-syntax` with an older version, that is going to cause an error with the updated CFML syntax which expects the up to date JavaScript syntax file now.
