### ISSUE TITLE
donate

### ISSUE THREAD

**Issue by itimgit** [jcberquist/sublimetext-cfml#15]
I'm so happy with this plugin, I wan't to give you some money! How can I donate?

**Comment by jcberquist** [comment]
Thank you! I am glad you like it. I don't have an easy way for donations set up, and, honestly, I don't really want them for this project. I am glad when it helps people and I do like hearing about it - so I appreciate that you wrote, but the thanks is enough!

**Comment by itimgit** [comment]
If you are ever in Amsterdam I will buy you a beer, or diner :) You rule!

**Comment by jcberquist** [comment]
:+1:

**Comment by mjhagen** [comment]
If you are, I'll join! :)
