### ISSUE TITLE
Error Loading Syntax File

### ISSUE THREAD

**Issue by rzeiss** [jcberquist/sublimetext-cfml#150]
I just updated my Sublime Text to build 4186, on my Windows 11 computer.

When I open a Coldfusion file,  xxxxx.cfm, I get this error...

**Error loading syntax file
Packages/CFML/syntaxes/cfml.sublime-syntax
Apparent recursion within a a with_prototype-action: 25000 context sanity limit hit****

I have tried removing the CFML package and reinstalling, same error occurs.

I uninstalled Sublime Text, via the Control panel, and I renamed the old folder that contained the Sublime text files and folders in Windows.  Then I downloaded 4186, installed it, and ran it.  Reinstalled package control, and installed the CFML package.
When I open a CFM file, the error is still there.

How do I fix this ?  We can't use Sublime Text and all work has stopped.

I am a long time user of Sublime Text.

Any assistance you can provide would be appreciated.

Bob Zeiss
rzeiss@att.net

**Comment by jcberquist** [comment]
Hi, could you please see https://github.com/jcberquist/sublimetext-cfml/issues/149 - I am working on an update, and will try to get it out soon. In the meantime, you will need to override the JavaScript Syntax that ships with Sublime Text as specified in that issue.

**Comment by rzeiss** [comment]
I have read it, but can you explain a little more how to do this.  Not clear to me.

**Comment by rzeiss** [comment]
Thanks for responding.I read 149, but it was not clear where I get the legacy JavaScript package or what the name of the package and how do I install?  Kill the other one first?BobOn Dec 17, 2024, at 4:41 PM, John Berquist ***@***.***> wrote:﻿
Hi, could you please see #149 - I am working on an update, and will try to get it out soon. In the meantime, you will need to override the JavaScript Syntax that ships with Sublime Text as specified in that issue.

**Comment by rzeiss** [comment]
Working now. Thanks.BobOn Dec 17, 2024, at 4:41 PM, John Berquist ***@***.***> wrote:﻿
Hi, could you please see #149 - I am working on an update, and will try to get it out soon. In the meantime, you will need to override the JavaScript Syntax that ships with Sublime Text as specified in that issue.

**Comment by rzeiss** [comment]
I saw your changelog comment... I thought it was working fine at that time, but later discovered the error was still present.
Knowing it was a JavaScript issue, I found a package called "Better JavaScript" and installed it.
This eliminated the error, and produced some good looking syntax highlight.

Thank you for the support and assistance.  Sublime Text 4186 rocks.

**Comment by MiY4MOTO** [comment]
> I saw your changelog comment... I thought it was working fine at that time, but later discovered the error was still present. Knowing it was a JavaScript issue, I found a package called "Better JavaScript" and installed it. This eliminated the error, and produced some good looking syntax highlight.
> 
> Thank you for the support and assistance. Sublime Text 4186 rocks.

I had a similar issue today with my Mac version of Sublime Text 4186 and managed to resolve it using your fix above. However I've noticed that any <script> block within a CF page no longer has any js syntax highlighting. Is this the case for you?

**Comment by jcberquist** [comment]
With `v0.31.0` syntax highlighting should work again in the latest Sublime Text stable version 4186. The JavaScript syntax highlighting now depends on explicitly on the default JavaScript syntax file at `Packages/JavaScript/JavaScript.sublime-syntax` - so it should not matter what other JavaScript package you install so long as it does not override the default package.
