### ISSUE TITLE
Doesn't recognise cfc's in returntype or cfargument type

### ISSUE THREAD

**Issue by jevans-gp** [jcberquist/sublimetext-cfml#16]
I'm loving the ability to look up my CFC's from `createObject`, incredible functionality.  Could you also extend it to the returntype in `cffunction` and the type in `cfargument`?

**Comment by jcberquist** [comment]
Do you specify the full dot path in the `returntype`, and `type`? If so, I think it would be possible. I will take a look when I have time.

**Comment by jevans-gp** [comment]
examples:

`<cfargument name="memberObj" type="com.wld.core.member.Member"
required="true" hint="The member object">`

and

`<cffunction name="init" access="public" output="false"
returntype="com.wld.core.payment.General">`

On 19 February 2016 at 14:26, jcberquist <notifications@github.com> wrote:

> Do you specify the full dot path in the returntype, and type? If so, I
> think it would be possible. I will take a look when I have time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcberquist/sublimetext-cfml/issues/16#issuecomment-186235310>
> .
>



-- 
Jared Evans
Developer
Venntro Media Group Limited

Venntro.com

-- 


Venntro Media Group is a limited company registered in England and Wales. 
Registered number: 04880697. 
Registered office: Minton Place, Victoria Street, Windsor, Berkshire, SL4 
1EG, United Kingdom.

**Comment by jcberquist** [comment]
@jevans-gp: This should be supported as of https://github.com/jcberquist/sublimetext-cfml/commit/c5cd531bd90eb544d7d972e6dd58f1c8d8cf2b0f. Can you confirm whether or not it works for you?

**Comment by jevans-gp** [comment]
Works perfectly, thank you
