### ISSUE TITLE
Ability to import custom tags via cfimport

### ISSUE THREAD

**Issue by cybersonic** [jcberquist/sublimetext-cfml#17]
I am not sure if this is even feasible, but we use a number of custom tags in our app. So at the top of most files we have:

```
<cfimport prefix="page" taglib="/ui/page">
<cfimport prefix="form" taglib="/ui/form">
```

it would be good to get completion when we do :
`
<page:... 
`

It should just (for the moment) list all the files that are in the `/ui/page` mapping 

The only way that I could see attributes working in these files is to check for 

`<cfparam name="attributes.x"...`

within the code

And to find out if it has an end tag search for:

`<cfif ThisTag.executionmode IS "end" ...`

I can see how this would be hard to implement though but just a new idea.

**Comment by jcberquist** [comment]
This does sound feasible to me from your description, and it is definitely the sort of thing I would like the package to support. I have to confess that I am not familiar with using custom tags in this fashion, however. So I will need to do a bit of research to make sure I understand what I am doing.

**Comment by cybersonic** [comment]
Cool. If you have any questions I am happy to help 

The other way of doing custom tags  with `<cf_tagname` is a bit of a nightmare for this kinda thing as you would have to just provide any file name (in the custom tag search paths rules) so that would be crazy really.

**Comment by jcberquist** [comment]
I have been looking at this, and I have a few questions (when you have time). 

First, it looks like `<cfimport>` only imports the root folder specified in the `taglib` attribute and  does not import files in sub-folders, is that correct? 

Would custom tags always be in a `.cfm` template or could one use a component in some way? In my limited testing, I could avoid a missing tag error by supplying a `.cfc` file in the taglib, but it didn't seem to do anything.

Finally, it would be convenient to scope all tags of the format  `<prefix:tagname>` as CFML custom tags, so that `#` characters work in attribute values, and it would also make it easier to offer completions for the tags. However, it looks like any tags in a template that have that format where the prefix is one that has not been specified in a `<cfimport>` are simply ignored by Lucee. Since they clearly don't have to be custom tags, my question is whether there is a use case for such tags (that are not CFML custom tags) that might show up in a `.cfm` file that I should be aware of?

**Comment by cybersonic** [comment]
> I have been looking at this, and I have a few questions (when you have time).

Of course! 

> First, it looks like <cfimport> only imports the root folder specified in the taglib attribute and does not import files in sub-folders, is that correct?

I am pretty sure that is right. that is how I use it anyhow. 
It could also import JSP tag libs, but I haven't encountered anyone doing that 

> Would custom tags always be in a .cfm template or could one use a component in some way? In my limited testing, I could avoid a missing tag error by supplying a .cfc file in the taglib, but it didn't seem to do anything.

Lucee allows you to have custom tags that end in a .cfc (http://blog.getrailo.com/post.cfm/cfc-custom-tag-example)
If the tag is not there you don't get an error, you just get the code displayed if I recall correctly. 

> Finally, it would be convenient to scope all tags of the format <prefix:tagname> as CFML custom tags, so that # characters work in attribute values, and it would also make it easier to offer completions for the tags. 

That would be great!

 As an aside, I would use any <cfparam>'s for attribute completion. So for example if you had:
mytag.cfm
```
<cfparam name="attributes.name" default="">
<cfparam name="attributes.age" default="">
```

You could do:
```
<cfimport prefix="bob" ...>

<bob:mytag name="" age="">
```
This leads people to properly document and param their tags too! 

> However, it looks like any tags in a template that have that format where the prefix is one that has not been specified in a <cfimport> are simply ignored by Lucee

That sounds right for Lucee. Although having said that in the docs it says:

http://docs.lucee.org/reference/tags/import.html
> If you import a CFML custom tag directory and specify an empty value, "", for this attribute, you can call the custom tags without using a prefix. You must specify and use a prefix for a JSP tag library.

so that sounds like a bug either in the docs or the implementation!  

> Since they clearly don't have to be custom tags, my question is whether there is a use case for such tags (that are not CFML custom tags) that might show up in a .cfm file that I should be aware of?

You need a prefix. There was a "bug" in ACF that you could put a blank prefix and therefore overwrite normal HTML tags, for example `<a href>` by using `<cfimport prefix="" taglib="/ui/tags">` and then creating a `a.cfm` file  but that is not in Lucee as far as I can remember. 

CFIMPORT is a strange one as it is meant to work with JSP tag libraries but I have always used it with customtags as my favourite way of using them.

**Comment by jcberquist** [comment]
Thanks for the blog post link! That is good to know. Reading it now I feel I may have read it before, but if I did it didn't stick. I will go ahead and include CFC's in the directory list.

My first thought regarding attributes was simply to do a search for any variables in the attributes scope in the file and offer those as attribute completions when entering the custom tag. (So, for example, given `attributes.name` anywhere in the custom tag file, `name` would be offered as an attribute completion.) Searching for them in `cfparam` tags would be more formal, but also a little more involved. I would also need to include the cfscript form of the param tag in my search. Still, it wouldn't be too hard, so is there reason to limit the search for attributes to params? (I suppose as you say it would force people who want completions to param their custom tag attributes.)

Regarding the implementation of this feature, my current thinking is to mimic the `.sublime-project` `cfc_folders` setting. So one would have a `custom_tag_folders` setting, which would contain an array of tag folders and the desired prefix to use them with like so:
```
"custom_tag_folders": [
    {"path": "/full/path/to/ui/page", "prefix": "page"}
]
```
Then in that project you would get offered `page` as a custom tag prefix when entering a tag in a CFML file and then after you have `<page:` you would get a list of the tags in the folder specified in the project settings. (So in other words as far as the completions go, whether or not you had `<cfimport prefix="page" taglib="/ui/page">` in a particular file would not affect whether or not you got the completions. This would be similar to how the CFC completions work.)

Does this sound like it would work for you?

**Comment by jcberquist** [comment]
Have you tried the custom tag completions that I added? I would like to close this issue, assuming it does what you need. Otherwise could you specify how it could be improved?

**Comment by cybersonic** [comment]
This is pretty damn neat! I just wished sublime would give you the ability to "guide" the user to add the custom_tag_folders property would be nice. Otherwise (as usual) you have to enable it via reading settings. 

Anyway, the feature looks like it works awesomely! Need to document it (if you haven't done so already) as I think it is great!
