### ISSUE TITLE
broken syntax color coding

### ISSUE THREAD

**Issue by hrzi** [jcberquist/sublimetext-cfml#18]
After the folowing valid syntax line the syntax coloring breaks:

&lt;cfqueryparam name=listGetAt(f.values, 1, "=") value=listGetAt(f.values, 2, "=")&gt;

**Comment by jcberquist** [comment]
I know that Lucee 5 has a setting that one can enable that causes the compiler to treat unquoted attribute values as variables, but I was not aware of this being possible anywhere else. I tried using `listGetAt()` as an attribute value in a tag on [TryCF.com](http://www.trycf.com/) with the various engine options, and it errored every time for me. Are you using Lucee 5?

**Comment by hrzi** [comment]
I actually use ...name=#listGetAt(f.values, 1, "=")#... but as i simplified the code example i deleted it, sorry.

**Comment by jcberquist** [comment]
Got it, and yes, that is currently not highlighted correctly. I will see what I can do.

**Comment by jcberquist** [comment]
The latest update should hopefully have resolved this issue. Can you let me know if it is fixed for you?

**Comment by hrzi** [comment]
After the update, issue is resolved. Great. thx

**Comment by jcberquist** [comment]
Thank you for confirming.
