### ISSUE TITLE
More syntax highlighting problems

### ISSUE THREAD

**Issue by hrzi** [jcberquist/sublimetext-cfml#19]
Hello, 

I found additional syntax highlighting problems:

1: `<cfif col eq 1>...` the col gets `meta.tag.script.cfml` scope and the and the syntax after that is broken.

2: `<cfset f.result = componentCall(`
		`component="#f.componentName#", `
		`method="#f.methodName#", `
		`argumentCollection="#f.arguments#"`
	`)>`
In the following example the "component" is highlighted wrong and the syntax after that is broken. If the call is in the same line (`<cfset f.result = componentCall(component="#f.componentName#", method="#f.methodName#", argumentCollection="#f.arguments#")>`) everything is ok.

**Comment by jcberquist** [comment]
Thanks for reporting these. I can confirm the first issue, but I am not seeing the second issue, could you get the scope assigned to `component` in the second example?

**Comment by hrzi** [comment]
For the second issue the scope is `... meta.class.declaration.cfml storage.type.class.cfml`. I should emphasise that the issue exists only if there is a linebreak after the `componentCall(` and each argument in in its own line.

**Comment by jcberquist** [comment]
Thanks, I was able to reproduce the second issue as well. These should both hopefully be fixed now.

**Comment by hrzi** [comment]
I can confirm that both issues are resolved now. Awsome work btw.
