### ISSUE TITLE
cfif tag does not auto-close

### ISSUE THREAD

**Issue by rossmd** [jcberquist/sublimetext-cfml#20]
I have the following in my user settings:

`{
	"cfml_between_tag_pair": "indent",
	"cfml_auto_insert_closing_tag": true,
	"cfml_non_closing_tags": ["cfabort","cfargument","cfbreak","cfcontinue","cfdump","cfelse","cfelseif","cfinclude","cfprocessingdirective","cfproperty","cfqueryparam","cfrethrow","cfreturn","cfset","cfthrow","cfparam","cflocation"]
}`

When I type <cfif> and close the tag, nothing happens.  I would expect a closing </cfif> tag and the cursor to indent on the next line.  I tried looking through the code to see if there was any way I could attempt to look into the issue myself and do a pull request, but I didn't get very far.

**Comment by jcberquist** [comment]
The close tag command does not currently fire for the `>` after a `cfif` tag, since it views the cursor as being in a cfscript context. I think I can remove that restriction, as I don't think it will affect anything else. 

In the keymap files I have the line:
```
{"key": "selector", "operator": "equal", "operand": "meta.tag.cfml - comment - source.cfml.script, meta.tag.custom.cfml - comment - source.cfml.script", "match_all":true}
```
changing that to:
```
{"key": "selector", "operator": "equal", "operand": "meta.tag.cfml - comment, meta.tag.custom.cfml - comment", "match_all":true}
```
should fix this.

**Comment by rossmd** [comment]
That worked great.  Thank you!

**Comment by jcberquist** [comment]
Thanks for pointing it out, I do plan on updating the default key maps as well.
