### ISSUE TITLE
function and tag completion should not be available in comments

### ISSUE THREAD

**Issue by cybersonic** [jcberquist/sublimetext-cfml#21]
At the moment, when I am writing comments the function and tag competition pop up. 

I posit that this should not happen as you are generally writing english (or whatever language) rather than code within a comment.

**Comment by jcberquist** [comment]
Thanks for reporting this. Is this in a cfscript context? If so, I think I know what is going on, I have been matching the sublime JavaScript syntax and there was a recent change where the newline character is no longer included in a `//` line comment. This has the side effect of letting auto complete be triggered when you are typing at the end of line comment. Does this match your situation? Either way, I think I will report it there and re-add the newline character to the comment scope here.

**Comment by cybersonic** [comment]
Yeah, this is in the cfscript context (in a component at any rate!)

**Comment by jcberquist** [comment]
Auto complete should no longer be triggered when typing at the end of a `//` comment line. Let me know if this fixes your issue.

**Comment by cybersonic** [comment]
Great fix. This doesn't automatically trigger the auto completion but if you DO want to write  function you *CAN* trigger it. 

Great work again sir!
