### ISSUE TITLE
Component function docs in comments

### ISSUE THREAD

**Issue by cybersonic** [jcberquist/sublimetext-cfml#23]
if you are document a cfscript based component it would be great to have a different way of showing doc comments vs normal comments, for example:
```
    /**
        Description of the item
        @attribute description of the attribute
    **/
    function someFunction(attribute){
    }
```

This comment should not just be greyed out, it would be great if it had bolding for @attribute and maybe italics for the description

This leads to developers seeing that it is "special"

**Comment by jcberquist** [comment]
Thanks for bringing this up @cybersonic. I know the original ST ColdFusion package uses the JavaDoc syntax (as an include), so I will at least do that. I would like to add something more specific to CFML though. I will try to get to this soon.

**Comment by mjhagen** [comment]
like highlighting `hint=""` attributes?

**Comment by jcberquist** [comment]
@cybersonic: I have added syntax highlighting for JavaDoc style comments. I matched the JavaDoc syntax, so that the syntax scopes applied are consistent with it. How the comments are actually styled will depend on the color scheme used.

**Comment by jcberquist** [comment]
@mjhagen: I would like to highlight those as well; I do support the following:
```
function myFunc() hint="function hint" {}
```
...but I didn't know that one could also hint function parameters in the same way. So support for those still need to be added.

**Comment by jcberquist** [comment]
@mjhagen: `hint=""` attributes for script function parameters should now have highlighting support. It is a bit tricky, but I think it will work unless you try something unusual.

**Comment by mjhagen** [comment]
I'm personally not a fan of the hint-attribute (but nice to see that it works). The javadoc highlighting is very nice :+1:
