### ISSUE TITLE
Add support to colorize SQL in queryExecute

### ISSUE THREAD

**Issue by andrew-dixon** [jcberquist/sublimetext-cfml#24]
Add support to colorize SQL in the queryExecute function in cfscript, e.g.

```
thisQuery = queryExecute("SELECT * from myTable WHERE myColumn = 1");
```
as well as across multiple lines, e.g.

```
thisQuery = queryExecute("
    SELECT * 
    from myTable 
    WHERE myColumn = 1
");
```

**Comment by jcberquist** [comment]
That is a good idea, I will see what I can do.

**Comment by jcberquist** [comment]
This should be working now (or whenever Package Control picks up the new release), so I am going to go ahead and close this. Let me know if there are any problems with it.

**Comment by andrew-dixon** [comment]
Superb, thanks so much.
