### ISSUE TITLE
CF Location Tag closes itself

### ISSUE THREAD

**Issue by Tigerlady** [jcberquist/sublimetext-cfml#25]
When using the cflocation tag inside another tag it tries to close itself.  Ok so let me explain.

`if I type an opening cfif statement then a cflocation tag then try to close the cfif statement instead of the cfif being closed it closes the cflocaiton tag which shouldn't have a closing tag. 

<cfif isDefined(mytest)>
<cflocation url="mypage.cfm">
</cflocation>
</cfif>`

**Comment by jcberquist** [comment]
Thanks! Which tags are closed and which are not is controlled by a package setting (imaginatively named `cfml_non_closing_tags`) - you can see the default tag list by going to `Preferences -> Package Settings -> CFML -> Settings - Default` or by opening the command palette and searching for `CFML: Settings - Default`. Right now `cflocation` is missing from the list, and I will add it in. In the meantime you can override the tag list by opening up the `Settings - User` file (found in the same way) and copying in the `cfml_non_closing_tags` setting from the default settings file, and then editing it there.

**Comment by jcberquist** [comment]
The latest release (0.10.0) has `cflocation` added to the non closing tag list. Thanks!
