### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by seancoyne** [jcberquist/sublimetext-cfml#26]
Would it be possible to support relative paths (for mappings, cfc folders & custom tags) in the .sublime-project file?

Example:
```json
{
	"folders": [ { "path": "." } ],
	"mappings": [
		{ "mapping": "/example", "path": "./path/to/example" }
	]
}
```

so the path for the mapping would be relative to the location of the .sublime-project file?

This would make the sublime-project file more portable and easier to use for teams w/ people on different platforms.

**Comment by jcberquist** [comment]
That makes sense, I will try to work on this soon.

**Comment by jcberquist** [comment]
This should be working as of the latest release (0.10.0). Please let me know if you encounter any problems.

**Comment by seancoyne** [comment]
I see an error in the console and the completions for custom tags which was working previously no longer works (relative or absolute path)

```
Traceback (most recent call last):
  File "src.custom_tags.custom_tags in /Users/sean/Library/Application Support/Sublime Text 3/Installed Packages/CFML.sublime-package", line 39, in index_project
  File "src.custom_tags.custom_tags in /Users/sean/Library/Application Support/Sublime Text 3/Installed Packages/CFML.sublime-package", line 101, in generate_tag_map
KeyError: 'tag_name'
```

**Comment by seancoyne** [comment]
Hmmm, might be something to do w/ my files or configuration.  I commented out the entire custom_tag_folders array except for one item and it functions fine.  I'll see if i can narrow it down.

**Comment by seancoyne** [comment]
OK seems to be 3 specific directories of custom tags in my setup.  Is there a way to put the plugin in a debug mode or something so I can see more details in the error messages?  Maybe I can track down which specific file(s) are causing the problem.

**Comment by jcberquist** [comment]
Do you see any console messages saying that the plugin is unable to read a file? It would be a message starting with `CFML: unable to read file - ` and then the full file path it tried to read.

**Comment by seancoyne** [comment]
Yes.  One example is from cfUniform 

https://github.com/QuackFuzed/cfUniForm/blob/develop/tags/forms/cfUniForm/countryCodes.cfm

I'm running an older version but this file looks the same as mine.

It is also having trouble loading tags from FarCry's core tag library, specifically displayTray.cfm

https://github.com/farcrycore/core/blob/p720/tags/core/displayTray.cfm

and objectStatus.cfm

https://github.com/farcrycore/core/blob/p720/tags/navajo/objectStatus.cfm

Hope that helps.

**Comment by jcberquist** [comment]
So these are definitely the source of the key errors, I should fix that so that when it is unable to read a file it doesn't cause a key error. But it would be nice to know why it can't open those files. Can you confirm that the file paths it prints to the console are valid ones?

**Comment by seancoyne** [comment]
Yes, they are valid paths

**Comment by jcberquist** [comment]
Can you try reading those tag files (using the paths printed in the console error messages) from the console to see if you can get more error message detail:
```
>>> f= open('/file/path/to/tag.cfm', 'r')
>>> f.read()
>>> f.close()
```

**Comment by seancoyne** [comment]
```
>>> f= open('/Users/sean/Sites/bcp3/plugins/orliveCaseStudies/tags/forms/cfUniForm/countryCodes.cfm', 'r')
>>> f.read()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3571: ordinal not in range(128)
>>> f.close()
```

**Comment by seancoyne** [comment]
Tried a few other files they all show the same error just varying positions and which byte it cannot read (0xef, 0xc3, etc)

**Comment by jcberquist** [comment]
Could you try setting the result of the read in the second line to a variable (`temp = f.read()`) instead of just reading it to the console? It is not clear to me if the error you see is coming when the file is read in the first place, or when it tries to print to the console. I am not sure why it would be using the `ascii` codec to decode the file, so the error that you see might be an error occuring when it tries to print to the console.

**Comment by seancoyne** [comment]
```
>>> f= open('/Users/sean/Sites/bcp3/core/tags/navajo/objectStatus.cfm', 'r')
>>> temp = f.read()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 11723: ordinal not in range(128)
>>> f.close()
```

**Comment by jcberquist** [comment]
So my understanding of the situation is as follows:
You are on OSX, in which the default python file encoding is `US-ASCII` You can confirm this by running from the console:
```
>>> import locale
>>> locale.getpreferredencoding()
```
This means that the file open command tries to use the ascii module to read the file, but there is a non-ascii character in there (in the `countryCodes.cfm` file, you have `ÅLAND ISLANDS`. Windows cp1252 encoding doesn't read this correctly either, but it also doesn't error.

Could you try the following:
```
f= open('/Users/sean/Sites/bcp3/plugins/orliveCaseStudies/tags/forms/cfUniForm/countryCodes.cfm', 'r', encoding='utf-8')
f.read()
f.close()
```
I think that will work. If it does, I might try either always using utf-8 when reading files, or falling back to that if the default encoding doesn't work.

**Comment by seancoyne** [comment]
that worked

```
>>> f= open('/Users/sean/Sites/bcp3/plugins/orliveCaseStudies/tags/forms/cfUniForm/countryCodes.cfm', 'r', encoding='utf-8')
>>> f.read()
'<cfsilent>\n<!--- \nfilename:\t\t\ttags/forms/UniForm/CountryCodes.cfm\ndate 
... the rest redacted ...'
>>> f.close()
```

**Comment by jcberquist** [comment]
I am hoping the last update fixed the file read issue, can you confirm?

**Comment by seancoyne** [comment]
It did thanks for your help!
