### ISSUE TITLE
Syntax highlighting of void return type in script

### ISSUE THREAD

**Issue by mjhagen** [jcberquist/sublimetext-cfml#27]
`void` is seen as `embedding.cfml source.cfml.script meta.class.body.cfml keyword.operator.cfml` and not as `embedding.cfml source.cfml.script meta.class.body.cfml meta.function.declaration.cfml storage.type.return-type.void.cfml` when omitting the storage modifier.

**Comment by jcberquist** [comment]
Thanks @mjhagen!
