### ISSUE TITLE
variable_names cannot contain "."

### ISSUE THREAD

**Issue by seancoyne** [jcberquist/sublimetext-cfml#28]
It seems that the variable_names key for cfc_folders cannot contain a period (.). Example:

```json
{
  "accessors": false,
  "path": "./path/to/lib",
  "variable_names": [ "application.lib.{cfc}" ]
},
```

Doesn't show completions when I have application.lib.cfc. 

If I change this to just "{cfc}" then I see completions.

Is it possible to get the variable_names feature to work with nested structures as the full variable name?

**Comment by jcberquist** [comment]
I took a look and I think this is doable. The way it works right now is when you type a `.` in cfscript, the plugin looks at what came immediately before (excluding whitespace). If it is a method call, or an object property, it keeps going until the dot chain terminates. Each piece of the path is contained in array - so you might have `['myService','lib','application']`. For the completions it walks through the array to see if anything there is not a method call and matches a cfc_folder variable name and if something is found it immediately returns with the corresponding completions.

I think what I can do is check that whole array first, and then the parts of it. So for the example above. I could first check for a variable name like `application.lib.myService` then for `lib.myService`, and finally for `myService`. So the longer chain will be used if found. I don't think that will break anything.

**Comment by seancoyne** [comment]
Working! 👍  Thanks!
