### ISSUE TITLE
Typed arrays break colour coding

### ISSUE THREAD

**Issue by cybersonic** [jcberquist/sublimetext-cfml#3]
If I have a typed array as my return syntax colouring breaks, so for example this works:

    public User function getUser(){}

but this doesnt:

    public User[] function getUser(){}

**Comment by jcberquist** [comment]
I have pushed an update that should fix this. Thanks for reporting it!

**Comment by cybersonic** [comment]
I pulled but saw no new commits?

**Comment by jcberquist** [comment]
That is strange, it is in this commit: 
https://github.com/jcberquist/sublimetext-cfml/commit/7ec161c3a6dd809ab8dbb627543c06fee8cb5c73

I am not sure why that wouldn't show up for you.

**Comment by cybersonic** [comment]
How odd, it's here in the log history but when I updated it said no updates. PEBKAC methinks

**Comment by jcberquist** [comment]
Assuming you do actually have the update, did it fix the issue for you?

**Comment by cybersonic** [comment]
Not really.
<img width="384" alt="screen shot 2016-01-15 at 15 39 22" src="https://cloud.githubusercontent.com/assets/148252/12357145/31149822-bb9e-11e5-8773-caaa73b74445.png">
 I am checking at the moment.

**Comment by jcberquist** [comment]
Is it possible you have both the Lucee package and the CFML one installed? If so, the syntax in the Lucee package will overwrite the syntax in the CFML one, since they have the same file name (for this issue `cfscript.sublime-syntax` is the syntax file in question). ST loads files of the same name in different packages in descending alphabetical order, so the syntax file in the Lucee package would get used, and it hasn't been updated yet.

**Comment by cybersonic** [comment]
That was totally it! I moved lucee out of the way and that seems to do the trick. Although the highlight should extend to the `[]` too shouldnt it?
<img width="344" alt="screen shot 2016-01-15 at 16 34 51" src="https://cloud.githubusercontent.com/assets/148252/12358601/eb6eb908-bba5-11e5-8abf-ba8d06809952.png">

**Comment by jcberquist** [comment]
Glad it is working!

I was torn about highlighting the brackets, but I ended up copying what the "official" Java syntax does. I am open to changing it - I just had to decide one way or the other, and so it matches Java at the moment.

**Comment by cybersonic** [comment]
I guess it makes sense. The more I look at it the more OK it is! Awesome work fella!
