### ISSUE TITLE
CFC folders not indexing

### ISSUE THREAD

**Issue by GiancarloGomez** [jcberquist/sublimetext-cfml#30]
There appears to be an issue when Sublime tries to index the cfc_folders. This worked before and now it fails, maybe you can give an insight on this?

The error I see in the console is as follows:
Exception in thread Thread-6:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "src.model_index.cfc_index.cfml_components in /Users/jc/Library/Application Support/Sublime Text 3/Installed Packages/CFML.sublime-package", line 50, in run
  File "src.model_index.cfc_index.cfml_components in /Users/jc/Library/Application Support/Sublime Text 3/Installed Packages/CFML.sublime-package", line 101, in parse_cfc_file_string
AttributeError: 'list' object has no attribute 'subkey'

I am on Sublime 3 Build 3114

**Comment by GiancarloGomez** [comment]
I don't know if maybe support for this was dropped but I did a couple of tests with basic CFC and I used the bad habit of setting component / function attributes inside the JavaDoc statement as allowed in ACF. So if I have a function with the following it will fail indexing.

`
/**
* @hint This is a test
*/
public function init(){}
` 

but this is ok
`
/**
* This is a test
*/
public function init(){}
`

**Comment by jcberquist** [comment]
Sorry about this. Could you please edit your comment above to put the code inside a fenced code block? I am not clear on what the exact code that is causing the fail is. 

This was definitely introduced by the last update, since it is happening when the plugin is trying to index a docblock.

**Comment by jcberquist** [comment]
Thanks, and I can see the issue in my code. I will try to get a fix for this out soon.

**Comment by GiancarloGomez** [comment]
Great! Thanks!!

**Comment by GiancarloGomez** [comment]
How long does it normally take to show up via Package Control?

**Comment by jcberquist** [comment]
PC performs checks at about 1 hour intervals, give or take.

**Comment by GiancarloGomez** [comment]
OK thanks!
