### ISSUE TITLE
Error when saving project settings - OS X

### ISSUE THREAD

**Issue by deanlaw** [jcberquist/sublimetext-cfml#32]
When trying to add a cfc_folders mapping to my project settings file, I receive the following error:

Exception in thread Thread-25:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "src.model_index.cfc_index.cfml_components in /Users/dean/Library/Application Support/Sublime Text 3/Installed Packages/CFML.sublime-package", line 50, in run
  File "src.model_index.cfc_index.cfml_components in /Users/dean/Library/Application Support/Sublime Text 3/Installed Packages/CFML.sublime-package", line 120, in parse_cfc_file_string
  File "src.model_index.cfc_index.cfml_components in /Users/dean/Library/Application Support/Sublime Text 3/Installed Packages/CFML.sublime-package", line 142, in get_accessors_metadata_dict
IndexError: string index out of range

I'm only having this issue on my OS X installation, not my Windows 10 install. Both are using version 0.12.1. Any thoughts on what might be the issue?

**Comment by jcberquist** [comment]
I am not sure why there is a difference between OSX and Windows. But that error indicates to me that when trying to parse the properties of a component, OSX is returning an empty (zero-length) property name string. This would cause the `IndexError` you see. This is probably the result of one of the regex searches I use not working correctly on OSX. 

It is most likely not going to be too easy for you to figure out which property is causing the issue. Certainly in a large project that would take a bit of work. When I have some time I will add some code to catch and rethrow this error, so that I can print the file name of the component that caused the error to the console. Then it should hopefully be easier to track down the root problem.

**Comment by jcberquist** [comment]
When 0.12.2 is available, please try adding the `cfc_folders` setting again. When it errors, you should get the file path of the component where the issue is printed to the console. Then you can try to determine which of the properties in that component is causing the underlying issue.

**Comment by deanlaw** [comment]
Ok, I updated to 0.12.2 and it appears that it is indexing some of my components but not others. I ran some tests and it seems to run into an issue if you define your ValidateThis rules directly in the component properties instead of an external XML file and if the rules have params (see below). I don't know if many people actually use this format, so it may be fringe case.

```
component displayname="Banner" output="false" persistent="true" table="tblBanner" extends="BaseORMService" {
	property name="bannerId" type="numeric" fieldtype="id" generator="native";
	property name="bannerName" type="string" length="150" vtDesc="Banner Name" vtRules='[
			{"type":"required"},
			{"type":"maxLength","contexts":"*",
				"params":[
					{"name":"maxLength","value":"150"}
				]
			}
		]';
	property name="bannerFileName" type="string" length="150" vtDesc="Banner File Name" vtRules='[
			{"type":"maxLength","contexts":"*",
				"params":[
					{"name":"maxLength","value":"150"}
				]
			}
		]';
	property name="bannerType" type="string" length="12" vtDesc="Banner Type" vtRules='[
			{"type":"required"},
			{"type":"maxLength","contexts":"*",
				"params":[
					{"name":"maxLength","value":"12"}
				]
			}
		]';
	property name="width" type="numeric" vtDesc="Banner Width" vtRules='[
			{"type":"integer"}
		]';
	property name="height" type="numeric" vtDesc="Banner Height" vtRules='[
			{"type":"integer"}
		]';
	property name="link" type="string" length="250" vtDesc="Banner URL" vtRules='[
			{"type":"url"},
			{"type":"maxLength","contexts":"*",
				"params":[
					{"name":"maxLength","value":"250"}
				]
			}
		]';
	property name="externalLink" type="boolean" sqltype="bit" default="0" dbdefault="0" notnull="true" vtDesc="External Link" vtRules='[
			{"type":"required"},
			{"type":"boolean"}
		]';
	property name="startDate" type="date" vtDesc="Start Date" vtRules='[
			{"type":"date"}
		]';
	property name="endDate" type="date" vtDesc="End Date" vtRules='[
			{"type":"date"}
		]';
	property name="dteCreated" type="date" ormtype="timestamp" update="false";
	property name="dteModified" type="date" ormtype="timestamp" ;
}
```

After removing the validation rules that had parameters, the component was able to be indexed.

```
component displayname="Banner" output="false" persistent="true" table="tblBanner" extends="BaseORMService" {
	property name="bannerId" type="numeric" fieldtype="id" generator="native";
	property name="bannerName" type="string" length="150" vtDesc="Banner Name" vtRules='[
			{"type":"required"}
		]';
	property name="bannerFileName" type="string" length="150";
	property name="bannerType" type="string" length="12" vtDesc="Banner Type" vtRules='[
			{"type":"required"}
		]';
	property name="width" type="numeric" vtDesc="Banner Width" vtRules='[
			{"type":"integer"}
		]';
	property name="height" type="numeric" vtDesc="Banner Height" vtRules='[
			{"type":"integer"}
		]';
	property name="link" type="string" length="250" vtDesc="Banner URL" vtRules='[
			{"type":"url"}
		]';
	property name="externalLink" type="boolean" sqltype="bit" default="0" dbdefault="0" notnull="true" vtDesc="External Link" vtRules='[
			{"type":"required"},
			{"type":"boolean"}
		]';
	property name="startDate" type="date" vtDesc="Start Date" vtRules='[
			{"type":"date"}
		]';
	property name="endDate" type="date" vtDesc="End Date" vtRules='[
			{"type":"date"}
		]';
	property name="dteCreated" type="date" ormtype="timestamp" update="false";
	property name="dteModified" type="date" ormtype="timestamp";
}
```

However, this disclosed another issue in that the implicit accessors are not being generated for persistent components. I will open up another ticket for this though.

**Comment by jcberquist** [comment]
This is extremely helpful, thanks! I will see what I can do to fix this.

**Comment by jcberquist** [comment]
0.12.3 is now available via Package Control. Could you update to that version, restart Sublime Text, and see if it fixes this issue?

**Comment by deanlaw** [comment]
That appears to have fixed both the indexing and the implicit accessors issues. Thanks!

**Comment by jcberquist** [comment]
Glad to hear it! Thank you very much for your help in working through the problem and figuring out the root cause.
