### ISSUE TITLE
Implicit accessors not being recognized

### ISSUE THREAD

**Issue by deanlaw** [jcberquist/sublimetext-cfml#33]
When a persistent component is indexed, the implicit accessors are not being recognized. Explicitly defined methods are found, but not the implicit accessors. I tried adding `"accessors": true` and `"accessors": "true"` to my cfc_folder mapping, but it did not help. The only time that the implicit accessors were generated was when I added `accessors="true"` directly in my component definition.

**Comment by jcberquist** [comment]
Thanks for pointing this out. Currently I only create implicit accessors when `accessors` is set to true on the component, or a property has `getter|setter` set to true. I do check if a component has `persistent` set to true, but I don't generate the accessors when it is. I will fix that.
