### ISSUE TITLE
[Feature Request] SQL strings

### ISSUE THREAD

**Issue by Shult2** [jcberquist/sublimetext-cfml#35]
It would be great if the syntax highlighter could detect SQL in strings like it does for queryExecute(). I frequently break out my SQL statements from queryExecute(), and form them in a string before calling the function. For example:

 	public query function someSQL(someArg, ID){
		var sql = '';
		var params = {};
		if(ARGUMENTS.someArg == 'all') {
			sql &= 'SELECT * FROM someTable';
		} else if(ARGUMENTS.someArg == 'name'){
			sql &= 'SELECT name FROM someTable';
		}
		sql &= 'WHERE ID = :ID'
		params.ID = { value = ARGUMENTS.ID, sqltype = "INTEGER"};
		return query = queryExecute(sql, params, {datasource = DSN});
	}
I don't know how many people program like this, but if there was some reg ex that could detect either 'sql =' or 'sql &=' before a string, and then treat the string as SQL, it would help quite a bit. Thanks!

**Comment by jcberquist** [comment]
Thank you for the request. This is possible, but if I added it, it would mean that a string assigned to a `sql` variable name in the fashion you mention (`sql =|&= ''`)  would always be highlighted as SQL. Though it does seem like it would be very likely to contain SQL, it of course is possible that it might not. 

I do know that the default Python syntax actually checks the starts of strings (other than double quoted ones) for the following keywords:
```
SELECT|INSERT|UPDATE|DELETE|CREATE|REPLACE|ALTER|WITH
```
If the string starts with one of those it is highlighted as SQL. Something along those lines is another possibility, or perhaps some combination of the two? I need to think about this.

**Comment by Shult2** [comment]
The Python-style fix you mention would definitely work. This would allow other programmers to have flexibility in how they name variables that store SQL strings as well. It is very unlikely that anyone would need a string that starts with a SQL reserved word in all caps unless they were actually writing SQL. I would add "DECLARE" to that list of reserved words.

**Comment by mrlife** [comment]
@jcberquist Would it be reasonable to add a couple more triggers? For consideration, it would be nice to have "TRUNCATE TABLE" and "BULK INSERT". I'm not sure how many others would benefit from this, though I have some sections where this would apply for me.

**Comment by jcberquist** [comment]
Adding those seems fine to me.

**Comment by mrlife** [comment]
@jcberquist This is pretty thorough now. The only other one I've used that prevents the color-coding is "DROP". Is that something you could consider adding?
