### ISSUE TITLE
Typing a Comma triggers tag suggestions

### ISSUE THREAD

**Issue by alanquinlan** [jcberquist/sublimetext-cfml#36]
Typing a comma anywhere in a cfm or cfc document triggers tag suggestions.

This is particularly a bother when writing clean code that spans across multiple lines.

I've checked various settings but I don't see how to turn this off as only an opening carrot '<' should be triggering this.

This even happens in a completely blank file with nothing else that should be setting this off.

![2016-08-02_1150](https://cloud.githubusercontent.com/assets/1110815/17337563/d73535f2-58a8-11e6-99f9-62bae230630c.png)

**Comment by jcberquist** [comment]
This doesn't happen for me. There are two settings I am aware of that control when the auto_complete is shown. With that `test.cfm` as the active view, could you open the console and run `view.settings().get('auto_complete_triggers')` and `view.settings().get('auto_complete_selector')`?

When I run these, I get (reformatted):
```
>>> view.settings().get('auto_complete_triggers')
[
	{'selector': 'source.cfml.script - string', 'characters': '.'},
	{'selector': 'source.cfml.script meta.function-call.support.createcomponent.cfml string.quoted', 'characters': '.'},
	{'selector': 'meta.class.inheritance.cfml', 'characters': '.'},
	{'selector': 'meta.tag.cfml - string - source.cfml.script', 'characters': ' '},
	{'selector': 'meta.tag.custom.cfml - string - source.cfml.script', 'characters': ': '},
	{'selector': 'meta.tag.script.cfml - string, meta.tag.script.cf.cfml - string, meta.class.declaration.cfml - string', 'characters': ' '}
]
>>> view.settings().get('auto_complete_selector')
'meta.tag - punctuation.definition.tag.begin, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc'

```

**Comment by jcberquist** [comment]
The other thing you could check is to enable logging of commands (using `sublime.log_commands(True)`) in the console, and then seeing if the `auto_complete` command is being run when you press `,`.

**Comment by alanquinlan** [comment]
Here's what I get (reformatted):
```
>>> view.settings().get('auto_complete_triggers')
[
{'characters': '.', 'selector': 'source.cfml.script - string'}, 
{'characters': '.', 'selector': 'source.cfml.script meta.function-call.support.createcomponent.cfml string.quoted'}, 
{'characters': '.', 'selector': 'meta.class.inheritance.cfml'}, 
{'characters': ' ', 'selector': 'meta.tag.cfml - string - source.cfml.script'}, 
{'characters': ': ', 'selector': 'meta.tag.custom.cfml - string - source.cfml.script'}, 
{'characters': ' ', 'selector': 'meta.tag.script.cfml - string, meta.tag.script.cf.cfml - string, meta.class.declaration.cfml - string'}
]

>>> view.settings().get('auto_complete_selector')
'meta.tag - punctuation.definition.tag.begin, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc'
```

**Comment by alanquinlan** [comment]
Alright I found the problem. It was another Package (SublimeCodeIntel).

I'm guessing there is some kind of conflict with the two packages.
It was only doing that for cfm and cfc files which it doesn't support but this problem seems to go away when I disable the package.

Weird.

Thanks!
