### ISSUE TITLE
[Feature Request] change ordering of auto suggest... make it smarter?

### ISSUE THREAD

**Issue by jevans-gp** [jcberquist/sublimetext-cfml#37]
![image](https://cloud.githubusercontent.com/assets/12134783/17358463/00bd996c-595a-11e6-827f-8a4c7e49bac5.png)

It would be really helpful if the auto-suggest/auto-complete was a bit smarter, so when i type `arguments.` in a function, it looks at the arguments available and suggests them before the cfml functions.

**Comment by jcberquist** [comment]
Nice idea. I think I can do this. There are some structural changes I want to make to the way I supply completions, and it will make this easier to do. So it won't be immediate, but I will get to it.

**Comment by mrlife** [comment]
@jcberquist I have a similar suggestion that doesn't appear to be addressed, but if there's a setting I'm missing, I apologize in advance :)

When typing an attribute name for a tag, it looks like the autosuggest doesn't offer up the attribute first. For example, if typing "n" after `<cfquery `, the string "numeric", which isn't an option for `cfquery`, is the highlighted suggestion, but I would expect "name" to be highlighted instead.

**Comment by jcberquist** [comment]
Unfortunately, I suspect that this is not a behavior that I can change. The auto suggest completions can come from various plugins, and I only control the ordering of what the CFML plugin itself returns. So if you use a package such as All Autocomplete, and it is providing its own set of completions, I can't control where its completions will be shown on the list.

**Comment by mrlife** [comment]
@jcberquist This is the only plugin I use; does that make a difference?

**Comment by jcberquist** [comment]
@mrlife It will limit the number of suggestions you get, but some suggestions are from ST itself, and those will be there even with no other plugins.
