### ISSUE TITLE
[Feature Request] 'Autoclose' pound signs

### ISSUE THREAD

**Issue by chapmandu** [jcberquist/sublimetext-cfml#39]
When entering `#` output `##` and place the cursor in between. 

The same behaviour as quotes.

**Comment by jcberquist** [comment]
If I understand you, this would be a relatively simple change, as it is controlled by the key binding file. For example in the Windows key binding file: [Default (Windows).sublime-keymap#L59-L68](https://github.com/jcberquist/sublimetext-cfml/blob/master/inputmaps/Default%20(Windows).sublime-keymap#L59-L68)


If you add that keybinding to your user key binding file, and then remove the `selection_empty` context setting, giving you the following, then it should behave the way you are asking:
```
{
    "keys": ["#"],
    "command": "insert_snippet",
    "args": {"contents": "#${0:$SELECTION}#"},
    "context": [
      {"key": "setting.auto_match_enabled", "operator": "equal", "operand":true},
      {"key": "selector", "operator": "equal", "operand": "string.quoted.double.cfml,string.quoted.single.cfml,meta.scope.cfoutput.cfml", "match_all":true}
    ]
}
``` 
I have gone back and forth on whether I want this behavior by default. With only this simple change, then if I have `#myvar` and I type `#`, I will get `#myvar##`. I am not sure I (personally) want that. There are ways around this, I think, but they will require a little more work.

**Comment by chapmandu** [comment]
Thanks for the snippet.. It does pretty much what I'm after.

Looks like you're all over this so I'l close.
