### ISSUE TITLE
Samples cfml

### ISSUE THREAD

**Issue by Alexey-T** [jcberquist/sublimetext-cfml#4]
Hi. I want to test syntax: maybe you can give sample CFML files? N files to test. Thanx.

**Comment by jcberquist** [comment]
Hi. If you are just looking for sample CFML files, I would recommend looking around on GitHub, maybe try:

https://github.com/search?l=ColdFusion&o=desc&q=coldfusion&s=stars&type=Repositories

and look for `.cfm` and `.cfc` files in those repositories. Good luck!

**Comment by Alexey-T** [comment]
Thanks
