### ISSUE TITLE
Don't format SQL in strings

### ISSUE THREAD

**Issue by mjhagen** [jcberquist/sublimetext-cfml#40]
This code:
`var sql_select = " SELECT DISTINCT chem.* , meta.* ";`

Gets formatted into this:
`var sql_select = " SELECT DISTINCT chem. * , meta. * ";`

Note the spaces before '*'. It doesn't break, but I could imagine it breaking on something else.

So maybe not format stuff inside strings, which I think you don't, but it might trigger because these strings are interpreted as SQL now.

**Comment by jcberquist** [comment]
Thanks for pointing this out. You are right, the `*` is scoped as `keyword.operator.star.sql` and the `keyword.operator` part of that is causing it to get formatted when CFML operators are formatted. I will need to exclude SQL from that formatting.
