### ISSUE TITLE
[ER] Don't suggest private methods on cfcs

### ISSUE THREAD

**Issue by mjhagen** [jcberquist/sublimetext-cfml#43]
Is it possible to differentiate between public and private methods on a cfc?
I've (only just now) setup a services directory in the `cfc_folders` feature and I have a bunch of private methods in them that I like to start with underscores unfortunately that makes them appear at the top.
If hiding isn't a good option, putting them below public methods might be better?

![image](https://cloud.githubusercontent.com/assets/100814/17929975/38115d08-6a04-11e6-9739-bc2c0ffc8c9d.png)

**Comment by jcberquist** [comment]
I will do this :). I already capture whether methods are private or public, so it shouldn't be too hard. I had to go and confirm for myself that it wasn't doing it already :grin: I guess I have them all there because they are needed when working in the file itself, or in a cfc that extends another that has private methods.

**Comment by mjhagen** [comment]
Thx! Awesome feature btw, don't know why I hadn't set it up.

**Comment by elpete** [comment]
So will private methods still be suggested in the cfc they are defined in or in a cfc that extends that one (maybe only when calling `super`)?

**Comment by jcberquist** [comment]
@elpete: That is my plan (I want them suggested where they are callable). I definitely don't want to remove private methods from the component completions altogether.

**Comment by jcberquist** [comment]
This should be taken care of in v0.15.0

**Comment by mjhagen** [comment]
Works like a charm, thanks! That was a pretty big commit, was it mostly refactoring?

**Comment by jcberquist** [comment]
Yeah, sorry about that. It is almost entirely tabs to spaces :) The bulk of the work in that branch was for creating this: https://github.com/jcberquist/sublimetext-cfml/blob/master/src/cfml_view.py 

I had decided I was going to use spaces going forwards for indentation, and got tired of converting files one by one as I was working on that, so I just finished off all of them. I will try to be better organized next time 😀

**Comment by mjhagen** [comment]
haha well, if it's _to_ spaces I'm all for it :)
