### ISSUE TITLE
CF Functions autocomplete broken

### ISSUE THREAD

**Issue by timsayshey** [jcberquist/sublimetext-cfml#46]
Code completion seems to be broken. When I type listFindNo.. or any other cf function, there is no autocomplete suggestions anymore. Did something change or is there a setting I need to enable?

**Comment by jcberquist** [comment]
Are you using Package Control? If you have the package installed, and you have a copy of it in your packages folder, they could be interfering with each other. Also, I would always start by checking the console in this situation to see if there are any error messages there. I presume you have the file syntax set correctly?

**Comment by timsayshey** [comment]
Weird, I just got the latest Sublime update and it's working again -- I'll let you know if the issue comes back -- thanks!

**Comment by jcberquist** [comment]
Thanks, this package doesn't handle being reloaded correctly, which is something I intend to work on - it is why I currently recommend closing and restarting ST when something has changed. It might be that you just ended up with things in an invalid state after the update to ST.
