### ISSUE TITLE
.cfm indentation 

### ISSUE THREAD

**Issue by l8nites** [jcberquist/sublimetext-cfml#47]
.cfm files don't respect my tab_size setting in Preferences.sublime-settings as follows
{
  "tab_size": 2
}
Tabs are being converted to 4 spaces
Is there another setting I'm missing?

**Comment by jcberquist** [comment]
I don't actually mess with any indentation settings in this package. There are a number of ST settings that affect indentation in the `Preferences.sublime-settings` file that it would be worth checking. You can visit this page: http://docs.sublimetext.info/en/latest/reference/settings.html?highlight=indent#whitespace-and-indentation to see a rundown of those settings.

You can see what ST is doing with the current file by looking at the bottom right of the ST window to the left of the file syntax setting. You will see something like `Tab Size: 4` or `Spaces: 4`, which tells you what ST is doing with the current file. You can adjust the tab settings for the current file by clicking on that. It might be that you have `detect_indentation` set to true in your settings file, and that would override your tab size setting for a file if ST thinks the file is currently indented with 4 spaces.

**Comment by l8nites** [comment]
Very helpful! Thanks!
