### ISSUE TITLE
[Feature request] Mark scopes as constants, not variables, for better syntax highlighting.

### ISSUE THREAD

**Issue by Thom1729** [jcberquist/sublimetext-cfml#48]
These items -- super, this, thread, and scopes -- are constants, not variables. Highlighting them as such 
helps them to stand out, making it easy to (for instance) skim a file and find nonlocal references. I have tried this out locally and I find it very helpful.

At cfscript.sublime-syntax:980, change "variable.language" to "constant.language".

    cfml-scopes:
      - match: \b(?i:super)\b
        scope: constant.language.super.cfml
      - match: \b(?i:this)\b
        scope: constant.language.this.cfml
      - match: \b(?i:thread)\b(?=[\[.])
        scope: constant.language.scope.cfml
      - match: |-
          (?x)
            \b(?i:(
            application|arguments|attributes|caller|cgi|client|cookie|flash|form|
            local|request|server|session|thistag|url|variables|self|static|argumentcollection
          ))\b
        scope: constant.language.scope.cfml

**Comment by jcberquist** [comment]
In using the scope `variable.language` I am following along with the official ST syntaxes. See, for example:

https://github.com/sublimehq/Packages/blob/master/Java/Java.sublime-syntax#L200-L201
https://github.com/sublimehq/Packages/blob/master/JavaScript/JavaScript.sublime-syntax#L1288-L1296

The colors you see and whether or not that scope stands out depends on the color scheme you are using. For instance, the default Monokai color scheme has a specific style for `variable.language`, and I find that `super`, `this`, etc. all stand out quite nicely when using it. I think the correct solution here would be to amend the color scheme you like to add a style for `variable.language` (or ask the color scheme maintainer to do so).

**Comment by Thom1729** [comment]
I'm using a modified version of Monokai, but for some reason mine doesn't highlight that. Perhaps I used an old version. Because common color schemes do highlight `variable.language`, my problem is solved by default.

Thanks for the quick reply.
