### ISSUE TITLE
"extends" attribute name not identified as entity.other.attribute-name

### ISSUE THREAD

**Issue by Thom1729** [jcberquist/sublimetext-cfml#49]
In the following:

    <cfcomponent name="MyComponent" extends="ParentComponent"></cfcomponent>

The word "extends" should be classified as `entity.other.attribute-name`. It is currently classified as:

- embedding.cfml
- source.cfml
- meta.tag.cfml
- meta.class.cfml
- meta.class.inheritance.cfml
- storage.modifier.extends.cfml

To fix, change syntaxes/cfml.sublime-syntax:76 from:

    1: storage.modifier.extends.cfml

to:

    1: entity.other.attribute-name storage.modifier.extends.cfml

I have verified that in Monokai, `extends` is still highlighted as a keyword.

The motivation for this fix is a script I'm writing that uses the syntax to process CFML code. It was skipping over the `extends` attribute because it was not classified as an attribute. Looking over the syntax, `extends` seems to be the only special case.

**Comment by jcberquist** [comment]
Thanks for pointing this it, your fix seems like a reasonable one. I will try to get it implemented soon.
