### ISSUE TITLE
html tag completion with multi cursor

### ISSUE THREAD

**Issue by maverck** [jcberquist/sublimetext-cfml#5]
I use multi cursor a lot, especially doing tables and html in general.
I've been having a problem which only seems to happen when i'm in CFML mode

essentially if i use multi cursor to type a bunch of <td> and then type </
normally it would close the td tag on all lines but instead it's only closing on the first line

for example
&lt;td&gt;&lt;/td&gt;
&lt;td&gt;&lt;
&lt;td&gt;&lt;
&lt;td&gt;&lt;
&lt;td&gt;&lt;
&lt;td&gt;&lt;
&lt;td&gt;&lt;
&lt;td&gt;&lt;
&lt;td&gt;&lt;
&lt;td&gt;&lt;

So im using ctrl+alt+up/down to select multiple lines, typing <td></

this works fine if i switch to HTML/Enhanced HTML

**Comment by jcberquist** [comment]
The update should address this, let me know if it fixed it for you.

**Comment by maverck** [comment]
Yes this is fixed. Thank you.
