### ISSUE TITLE
[Feature request] Have ORM object creation functions use indexed CFCs

### ISSUE THREAD

**Issue by mjhagen** [jcberquist/sublimetext-cfml#50]
This is a request to have this:

```
var test3 = entityLoadByPK( "foo", "someId" );
var test4 = entityLoad( "foo", {}, true );
var test5 = entityNew( "foo" );
```

provide the same functionality as this:

```
var test1 = new root.model.foo();
var test2 = createObject( "component", "root.model.foo" );
```

So, after calling any of the first functions, it should provide auto-completion and f1 help for those variables.

**Things I think might make this complicated**
- the CFCs are mapped using entityName, which can be changed
- the entities are in specific folders set using the application setting `this.ormSettings.CFCLocation`
- the entityLoad() method can return both an array and an object, it should only work for `unique=true`

**Comment by jcberquist** [comment]
Sounds good. I actually think this is very doable. We will see if I am right :grinning:

**Comment by jcberquist** [comment]
Hey @mjhagen, I am pushing out a release that supposedly supports this. Please test it for me and let me know how it goes!

**Comment by mjhagen** [comment]
Cool! Will do and I'll let ya know.

**Comment by jcberquist** [comment]
I am going to close this now, but please still comment if you do find problems.
