### ISSUE TITLE
Shortcut key - ctrl+alt+d (<cfdump>) not working

### ISSUE THREAD

**Issue by bsienn** [jcberquist/sublimetext-cfml#52]
ST3 shortcut key - ctrl+alt+d (cfdump) not working

OS: Windows 7 - 32bit
ST3 - Build - 3126
Fresh  Plugin Install with default settings.

**Comment by jcberquist** [comment]
The key binding file is what controls this behavior: https://github.com/jcberquist/sublimetext-cfml/blob/master/inputmaps/Default%20(Windows).sublime-keymap#L20-L38

If you are in a file where the syntax is set to `CFML` and <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>d</kbd> doesn't insert the cfdump tag, it is possible you have another plugin which overrides that key binding. I recommend opening the console in ST (<kbd>CTRL</kbd>+<kbd>\`</kbd>), and entering `sublime.log_commands(True)`. Then place the cursor in a file where the syntax is set to `CFML` and try the key binding again, and see what is logged to the console. If it were working properly, you would see:
```
command: insert_snippet {"contents": "<cfdump var=\"#${1:$SELECTION}#\">"}
```

**Comment by bsienn** [comment]
Thanks for the reply. Following your instructions in console I see "go_to_var_definition" on alt+ctr+d
I tried to find the binding for that event but I wasn't able to as I don't have much experience with ST.

For now I have copied the bindings in user settings and its working fine now.
Thanks again for your efforts on this plugin and for your reply.
