### ISSUE TITLE
[Feature Request] Use box.json to pick up testbox settings

### ISSUE THREAD

**Issue by cybersonic** [jcberquist/sublimetext-cfml#54]
At the moment we use the settings either from the user package settings of project settings file. If there already is a box.json file  the settings for running testbox should already be there. 

The box.json file would have 

```
    [
        ...
        "testbox"           : {
            "runner" : [
                { "cf10"    : "http://cf10cboxdev.jfetmac/testbox/tests/runner.cfm" },
                { "cf11"    : "http://cf11cboxdev.jfetmac/testbox/tests/runner.cfm" },
                { "lucee"   : "http://luceecboxdev.jfetmac/testbox/tests/runner.cfm" }
            ]
        }
    ]
```

Which should be enough to at least run the tests. We could also add any more info to that file no?

**Comment by jcberquist** [comment]
This sounds interesting. How do you envision the `box.json` file being discovered? Searching a project's root folders? Specifying it in the project file?

**Comment by cybersonic** [comment]
I would just search the root folders

**Comment by cybersonic** [comment]
It should be in the root folder. I think that should be enough?

At most it could be in a child folder but I would just use the root. (Until someone complains) :)

Mark Drew
- Sent by typing with my thumbs.

**Comment by jcberquist** [comment]
This certainly seems doable. I guess if using the `box.json` settings, I should add `reporter=JSON` to the url if it isn't there?

**Comment by jcberquist** [comment]
I think this should be supported now, but please let me know if you find issues with it.
