### ISSUE TITLE
Ability to use "cf_" for custom tag insight?

### ISSUE THREAD

**Issue by gruskada** [jcberquist/sublimetext-cfml#55]
I am really liking the custom tag insight - thank you for taking care of my last issue with this.

We don't actually call custom tags via `<cfimport>`, though, so right now I have to make up a prefix, get my tag insight, then change the start of the tag (i.e. "<page:") back to "<cf_".

I found that I don't need to actually use the `<cfimport>` tag at the top of the page, so I tried to just use "cf_" as my prefix. The console doesn't return any errors, but it also doesn't work.

It would be great if there was someway that once you type an underscore that it tries to search the custom tags that you've specified in the config file.

If this is crazy - no worries. I can write a quick macro or something to accomplish this.

**Comment by jcberquist** [comment]
What you are asking for is definitely doable. I currently set up the custom tag index to work through the prefixes specified in the project file, but I could also create an index that just uses the file/tag names and make use of that with `<cf_tag/>` style custom tags. I will try take a look at it soon.

**Comment by gruskada** [comment]
Works great - thank you!
