### ISSUE TITLE
Can't type a comma inside parenthesis

### ISSUE THREAD

**Issue by isapir** [jcberquist/sublimetext-cfml#56]
Since v0.19.0 I can not type a comma `,` inside `(` parenthesis `)` in `.cfm` file.

Also, closing `>` seems to have stopped working in some cases.

**Comment by jcberquist** [comment]
I am sorry to hear that, have you looked at issues #34 and #42?

In particular as I mentioned in those it would be helpful to know:

- did you download/git clone the package to install, or did you use Package Control?
- if you didn't use Package Control, what parent folder did you put it in, and what did you name it?
- if you close ST and then reopen it and look at the console do you see any errors reported there?
- if you run sublime.log_commands(True) from the console, and then try typing a `>` to close a tag or a `,` inside of a function call, what, if anything, is printed to the console?

In both cases, pressing those keys (in specific contexts) is supposed to run a command that both prints out that specific character to your file, but then also does other things (like inserting a closing tag). So if the command classes are not loaded properly by ST nothing will happen.

**Comment by isapir** [comment]
Thank you, @jcberquist , for your prompt reply.

I have installed the package long ago via Package Control.  The upgrade to v0.19.0 happened automatically.

After you posted your reply I removed the package via package control, and re-installed it via package control.

I then restarted ST and now the issue seems to have gone away.  I will report back if it happens again.

Thanks!
