### ISSUE TITLE
Unable to read local copy of CFDocs

### ISSUE THREAD

**Issue by mduey** [jcberquist/sublimetext-cfml#60]
I have a local copy of CFDocs and have added the path to it:
`"cfdocs_path": "C:/cfdocs/data/en/"`
in the settings.  However, I get an error when pressing F1:
```
Uh Oh!
I tried to load that doc for you but got this instead: 
Unable to read cfhtmlhead.json
```
The name of the tag changes when I select a different tag, so it is finding the file, it just can't read it.  Do I need JSON plugin to read them?
I am on v 0.19.0 and ST3 3126.
Thanks!

**Comment by jcberquist** [comment]
To get the full error message could you please try loading the file via the ST console? Try the following and see what error(s) you get:
```
>>> f = open("C:/cfdocs/data/en/cfhtmlhead.json", "r", encoding="utf-8")
>>> f.read()
>>> f.close()
```

**Comment by mduey** [comment]
Here is the content retrieved by the read (partially manually parsed):
```
'{\n\t
"name":"cfhtmlhead",\n\t
"type":"tag",\n\t
"syntax":"<cfhtmlhead text=\\"\\">",\n\t
"returns":"",\n\t
"related":[],\n\t
"description":" Writes text to the head section of a generated HTML page. It is\\n useful for embedding JavaScript code, or putting other 	HTML\\n tags, such as meta, link, title, or base in an HTML page\\n header.",\n\t
"params": [\n\t\t{"name":"text","description":"Text to add to the <head> area of an HTML 	page.","required":true,"default":"","type":"String","values":[]}\n\n\t],\n\t
"engines": {\n\t\t"coldfusion": {"minimum_version":"", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-	tags/tags-g-h/cfhtmlhead.html"},\n\t\t"lucee": {"minimum_version":"", "notes":"", "docs":"http://docs.lucee.org/reference/tags/htmlhead.html"},\n\t\t"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/tag/cfhtmlhead"},\n\t\t"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/tag/cfhtmlhead"}\n\t},\n\t"links": [\n\n\t]\n\n}\n'
```
Could be the \n\t tags getting in the way?

**Comment by jcberquist** [comment]
As you may know, the `\n` and `\t` are just Python's way of representing newline and tab characters contained in a string. They aren't a problem, I see the same when I run those lines.

That error message is specifically for reading the file from disk and comes from a try block where the only thing that happens is the following:
```
with open(full_file_path, "r", encoding="utf-8") as f:
    json_string = f.read()
```
So I find it puzzling that you can read the file successfully via the console, but the plugin fails to do so. I suppose you could just verify the `full_file_path` by running the following from the console (assuming you installed this plugin via Package Control, or manually into a folder named `CFML`):
```
>>> import CFML.src.utils as utils
>>> utils.get_setting("cfdocs_path")
```
and confirming that it returns `C:/cfdocs/data/en/`

**Comment by mduey** [comment]
I installed the plugin via Package Control.  
When I run the import code above, it returns the correct path:
`'c:\\cfdocs\\data\\en'`
However, if I set the cfdocs_path to a folder that does not exist:
`"cfdocs_path": "c:\\cfdocXX"`
I get the same error when pressing F1.  
Running the utils with the new bogus path returns the correct path ('c:\\cfdocXX' in this case).
I get the same Uh-Oh error no matter what I set the path to.

**Comment by jcberquist** [comment]
Can you ensure you have a trailing `\` after your your path? So getting the `cfdocs_path` setting returns `'c:\\cfdocs\\data\\en\\'`.

**Comment by mduey** [comment]
Doh!  That was it.  Trailing slashes fixed it.  Thanks for your quick responses and the great plugin!

**Comment by jcberquist** [comment]
Glad it is resolved, and thanks. I will try to update things in the future so that the file path works either way.

**Comment by jcberquist** [comment]
I would like to leave this issue open for now so that I remember to do that.

**Comment by jcberquist** [comment]
The trailing slash is now optional as of v0.20.0
