### ISSUE TITLE
Some pages are not getting parsed

### ISSUE THREAD

**Issue by KrunchMuffin** [jcberquist/sublimetext-cfml#61]
I have some templates that are not getting parsed and therefore no color coding. I believe it's only CFC's, and then only a couple that I have noticed. Started after 0.20.0 release i believe.

![image](https://cloud.githubusercontent.com/assets/1037197/20986925/a761df5c-bc98-11e6-8fcd-42295a3ce8be.png)

**Comment by jcberquist** [comment]
Have you confirmed that the syntax on those files is set to `CFML`? After the last update to the plugin, did you restart ST? Also, you might try closing and re-opening the file. I don't see anything in the syntax in your screenshot that should be a problem in itself. 

If you verify that a particular code syntax doesn't get highlighted (e.g. you can copy paste into a new file, and ensure the syntax is set to `CFML`, and it doesn't highlight properly), a minimal example of that syntax in text format for easy copy pasting would be very helpful for debugging.

**Comment by KrunchMuffin** [comment]
oh crap, I should have noticed. Yes it was set to latex. but why? Not something I would have changed.

**Comment by jcberquist** [comment]
Glad it was something simple. Given that it is easy to change the syntax for a file via the command palette, or via a plugin, the switch could have come from a variety of places. When the plugin is updated, I believe it gets disabled for a minute, and that could possibly have triggered a change in files you had open at the time.
