### ISSUE TITLE
503 Timeouts

### ISSUE THREAD

**Issue by timsayshey** [jcberquist/sublimetext-cfml#63]
As of a few minutes ago the auto documentation pop ups are timing out and causing a 503 error.

This is bringing our coding to a standstill because it happens every time we click a function.

Please advise.

Thanks,
Tim

**Comment by jcberquist** [comment]
@timsayshey: sorry to hear that, and sorry about the delay in getting back to you! I was traveling today, and my access to internet was limited. If the HTTP requests are timing out, you can set `cfml_hover_docs` to `false` in your user package settings to turn them off (see https://github.com/jcberquist/sublimetext-cfml#inline-documentation). The completion documentation popup can be disabled in the same way by setting `cfml_completion_docs` to `false` (see https://github.com/jcberquist/sublimetext-cfml#completions).

Alternatively, you can clone the cfdocs.org repo (https://github.com/foundeo/cfdocs) to a local drive and use the `cfdocs_path` setting to point to the data folder from the repository. With that setting in place documentation is loaded from the local copy and not fetched from GitHub. (This is also mentioned at https://github.com/jcberquist/sublimetext-cfml#inline-documentation.)

**Comment by timsayshey** [comment]
Thanks @jcberquist -- not sure if it was actually the docs -- turns out this correlated with a 2 hour downtime from GitHub
