### ISSUE TITLE
Error Loading Syntax file

### ISSUE THREAD

**Issue by kbajpai** [jcberquist/sublimetext-cfml#64]
After installation, I get the following error on Windows 10/SublimeText3, when I restarted ST3,

![screenshot 2017-01-26 11 21 18](https://cloud.githubusercontent.com/assets/813554/22342379/cd72a440-e3b9-11e6-8f78-f34e5d1e6e5d.png)

![screenshot 2017-01-26 11 27 24](https://cloud.githubusercontent.com/assets/813554/22342587/80a5f5ee-e3ba-11e6-8232-c09ec64e7798.png)

**Comment by jcberquist** [comment]
Sorry! Two possibilities occur to me. 

It might be possible that a particular file is causing trouble for the syntax, so did you have any files open when you installed the syntax and restarted Sublime Text? 

What I think is more likely though is the following: the CFML syntax includes the HTML syntax in it, which then includes the JavaScript and CSS syntaxes. If any of these syntaxes are not the default ones that come with Sublime Text, the combination of that and the CFML syntax might be causing the error. If you do not use the default HTML, JS, or CSS syntaxes could you let me know which one(s) you are using?

**Comment by kbajpai** [comment]
Clean install of ST3 fixed the problem, but wanted to report it.

**Comment by jcberquist** [comment]
Ok, thanks for letting me know.
