### ISSUE TITLE
Not found by package control

### ISSUE THREAD

**Issue by tomchiverton** [jcberquist/sublimetext-cfml#65]
Fresh install of Sublime 3.

Installed Package Control via instructions on https://packagecontrol.io/installation

CTRL-SHIFT-P select "package control install" and press enter.

Type 'coldfusion' with or without filter into the list that appears.

Nothing relevant found :-(

**Comment by jcberquist** [comment]
Sorry that you are having trouble. If I understand you, you are trying to install this via Package Control? If so, you will need to search for `cfml` in the list, since that is this package's name in Package Control.

**Comment by tomchiverton** [comment]
The instructions for installation are unclear then. Would be handy to link to package control installation instructions and say what to type after that? 
-- 
Tom

**Comment by tomchiverton** [comment]
https://github.com/jcberquist/sublimetext-cfml/pull/66

**Comment by jcberquist** [comment]
Thanks!
