### ISSUE TITLE
[Feature Request] Option to add two # when pressing that key

### ISSUE THREAD

**Issue by mrlife** [jcberquist/sublimetext-cfml#67]
It would be helpful to have two # inserted when pressing that key, with the cursor between them, as an option. This is something I'm used to from a previous CFML package. I'm going to use your package either way, so no worries if it's not something you can fit in.

**Comment by jcberquist** [comment]
Could you take a look at https://github.com/jcberquist/sublimetext-cfml/issues/39? I think that would give you what you want.

**Comment by mrlife** [comment]
That is pretty close, and thanks for providing the code snippet. I think the previous CFML package I used, which is no longer supported, would add two # surrounding the highlighted code, sort of how this package does it with single or double quotes.

**Comment by jcberquist** [comment]
Could you provide an example where pressing <kbd>#</kbd> does not surround highlighted code with `#....#` where you would have expected it to?

**Comment by mrlife** [comment]
It looks like it works when it should but not outside of a string or the context of a tag or function. Thanks for clearing it up for me!

**Comment by jcberquist** [comment]
Glad it is cleared up. Let me know if you encounter a situation where it doesn't work as you expect.
