### ISSUE TITLE
Code formating

### ISSUE THREAD

**Issue by eric00000007** [jcberquist/sublimetext-cfml#68]
Thanks for your work. I use it everyday. I have a request about code formatting. Since using sublime I always have trouble with automatic code formating 

-  `<cfelse><cfelseif>`, which have an extra identation after

- tags without closing tag like `<cfset>` which have an extra identation after, except if it is written like so `<cfset />`

- Coldfusion tags into `<javascript></javascript>` HTML tag have no proper code color and indentation

I  read Sublime documentation and code to find solution, but I am lost and found no solution so far.

**Comment by jcberquist** [comment]
I am afraid I am not following you exactly. Would it be possible for you to give some concrete examples of your bullet points above? You mention automatic code formatting, are you referring to the "Reindent Lines" command or something else?

**Comment by eric00000007** [comment]
yes exactly, Reindent Lines (shift + alt + f)
It does not work properly for me on Windows. 
reading http://docs.sublimetext.info/en/latest/reference/metadata.html#related-api-functions
I went on cfml-indent.tmPreferences to test it https://regex101.com/r/OHB2o3/2

maybe escaping slash is missing in the regexp... 
I am trying to test it on sublime, I reinstall everything on a new system but now the "reindent lines" is not working after sublime and cfml package fresh installation

**Comment by eric00000007** [comment]
I edit the file metadata\cfml-indent.tmPreferences
and add 2 lines into the regexp of decreaseIndentPattern, but this has no effect. I am not sure how to test this preferences. It seems to me that it never use this file even if I restart sublime, delete the cache ...
See the regexp https://regex101.com/r/aGH3Hl/1
See similar issue http://blog.lotech.org/2013/04/fixing-lua-indenting-in-sublime-text.html
`
	<key>decreaseIndentPattern</key>
		<string>(?x)
		^\s*
		(
		&lt;\/(cf)
		[A-Za-z0-9]+\b[^&gt;]*&gt;
		|-?--&gt;
		|&lt;cfelseif\b[^&gt;]*&gt;
		|&lt;cfelse\b[^&gt;]*&gt;
		)</string>
`

**Comment by eric00000007** [comment]
I change the file `cfml.tmPreferences` and added few lines and it works for `cfelse `and `cfelseif`. 
I still have the issue with tags without closing tag like <cfset> which have an extra identation after, except if it is written like so <cfset />.

`cfml.tmPreferences`
```XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>cfml</string>
	<key>scope</key>
	<string>embedding.cfml - source.cfml.script, text.html.cfml</string>
	<key>settings</key>
	<dict>
		<key>shellVariables</key>
		<array>
			<dict>
				<key>name</key>
				<string>TM_COMMENT_START</string>
				<key>value</key>
				<string>&lt;!--- </string>
			</dict>
			<dict>
				<key>name</key>
				<string>TM_COMMENT_END</string>
				<key>value</key>
				<string> ---&gt;</string>
			</dict>
      <dict>
				<key>name</key>
				<string>TM_LINE_TERMINATOR</string>
				<key>value</key>
				<string>&gt;</string>
      </dict>
		</array>
		<key>decreaseIndentPattern</key>
				<string>(?x)^\s*
					(
					&lt;\/(cf)
					[A-Za-z0-9]+\b[^&gt;]*&gt;
					|-?--&gt;
					|&lt;cfelseif\b[^&gt;]*&gt;
					|&lt;cfelse\b[^&gt;]*&gt;
					)</string>
					<key>increaseIndentPattern</key>
					<string>(?x)^\s*
						&lt;
						(?!
						(?i:!---?|\/|cfset|cfparam|cfdump|cfargument|cfabort
						|cfimport|cfcontent|cfbreak|cfinclude|cfcatch|cfcontinue
						|cflocation|cfsetting|cffile|cflog|cfobject|cfinvoke|cfimport
						|cfforward|cfreturn|cfthrow|cfproperty|cfhtmlhead|cfheader
						|cftrace|cfelse|cfelseif
						)
						)
						[^&gt;]*
						&gt;
						\s*$</string>
	</dict>
	<key>preserveIndent</key>
					<false/>
</dict>
</plist>
```

**Comment by jcberquist** [comment]
Thanks for looking into this. Looking over what is going on, I think there is some interaction with the HTML syntax going on, where the `batchDecreaseIndentPattern` and `batchIncreaseIndentPattern` settings from that package affecting the indenting going on for CFML tags. 

Changing the `cfml-indent.tmPreferences` file to the following (and keeping everything else as it is in the Github repo) does seem to result in better behavior - though there are still some issues with block comments.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>cfml-indent</string>
    <key>scope</key>
    <string>embedding.cfml, embedding.cfml text.html.cfml</string>
    <key>settings</key>
    <dict>
        <key>decreaseIndentPattern</key>
        <string>(?x)
            ^\s*
            (
                &lt;/(cf)[A-Za-z0-9]+\b[^&gt;]*&gt;
                |&lt;cfelse[^&gt;]*&gt;
            )
        </string>
        <key>batchDecreaseIndentPattern</key>
        <string>(?x)
            ^\s*
            (
                &lt;/(cf)[A-Za-z0-9]+\b[^&gt;]*&gt;
                |&lt;cfelse[^&gt;]*&gt;
            )
        </string>
        <key>increaseIndentPattern</key>
        <string>(?x)
            ^\s*
                &lt;
                (?!
                    (?i:!---?|/|cfset|cfparam|cfdump|cfargument|cfabort
                    |cfimport|cfcontent|cfbreak|cfinclude|cfcatch|cfcontinue
                    |cflocation|cfsetting|cffile|cflog|cfobject|cfinvoke|cfimport
                    |cfforward|cfreturn|cfthrow|cfproperty|cfhtmlhead|cfheader
                    |cftrace
                    )
                )
                [^&gt;]*
                &gt;
            \s*$
        </string>
        <key>batchIncreaseIndentPattern</key>
        <string>(?x)
            ^\s*
                &lt;
                (?!
                    (?i:!---?|/|cfset|cfparam|cfdump|cfargument|cfabort
                    |cfimport|cfcontent|cfbreak|cfinclude|cfcatch|cfcontinue
                    |cflocation|cfsetting|cffile|cflog|cfobject|cfinvoke|cfimport
                    |cfforward|cfreturn|cfthrow|cfproperty|cfhtmlhead|cfheader
                    |cftrace
                    )
                )
                [^&gt;]*
                &gt;
            \s*$
        </string>
    </dict>
</dict>
</plist>
```

I would recommend not editing the file in the `Packages` directory directly, but placing a copy in your user folder - it will override the one in the package directory.

**Comment by eric00000007** [comment]
Thanks,
The trouble was with the scope ? I could not find a documentation on that.
I tested the code and I came with some issue with html tags. I removed the `(cf)` in `batchDecreaseIndent`. Actually I removed it also in `decreaseIndentPattern `to be consistent. I also added cfmodule (I still have code with that). Now the indentation seems much better !
``` XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>name</key>
		<string>cfml-indent</string>
		<key>scope</key>
		<string>embedding.cfml, embedding.cfml text.html.cfml</string>
		<key>settings</key>
		<dict>
			<key>decreaseIndentPattern</key>
			<string>(?x)^\s*
				(
				&lt;/
				[A-Za-z0-9]+\b[^&gt;]*&gt;
				|&lt;cfelse\b[^&gt;]*&gt;
				)
			</string>
			<key>batchDecreaseIndentPattern</key>
			<string>(?x)
				^\s*
				(
				&lt;/[A-Za-z0-9]+\b[^&gt;]*&gt;
				|&lt;cfelse[^&gt;]*&gt;
				)
			</string>
			<key>increaseIndentPattern</key>
			<string>(?x)
				^\s*
				&lt;
				(?!
				(?i:!---?|/|cfset|cfparam|cfdump|cfargument|cfabort
				|cfimport|cfcontent|cfbreak|cfinclude|cfcatch|cfcontinue
				|cflocation|cfsetting|cffile|cflog|cfobject|cfinvoke|cfimport
				|cfforward|cfreturn|cfthrow|cfproperty|cfhtmlhead|cfheader
				|cftrace|cfmodule
				)
				)
				[^&gt;]*
				&gt;
				\s*$
			</string>
			<key>batchIncreaseIndentPattern</key>
			<string>(?x)
				^\s*
				&lt;
				(?!
				(?i:!---?|/|cfset|cfparam|cfdump|cfargument|cfabort
				|cfimport|cfcontent|cfbreak|cfinclude|cfcatch|cfcontinue
				|cflocation|cfsetting|cffile|cflog|cfobject|cfinvoke|cfimport
				|cfforward|cfreturn|cfthrow|cfproperty|cfhtmlhead|cfheader
				|cftrace|cfmodule
				)
				)
				[^&gt;]*
				&gt;
				\s*$
			</string>
		</dict>

	</dict>
</plist>
```

**Comment by jcberquist** [comment]
Yeah, good catch regarding the HTML tags. With the change I suggested above, for HTML in CFML documents, the rules in the `cfml-indent.tmPreferences` file take precedence. So I might need to add the HTML rules to it. (Similar to what you ended up doing above.)

**Comment by eric00000007** [comment]
The indentation looks nice now, just with `Shif + Alt + F`
Finally !

**Comment by jcberquist** [comment]
@eric00000007: I have put up new settings that include the HTML indent settings as well. Thanks for your help. You may still want to override the default file, since I did not include `cfmodule`. (I was torn about it but since it can be used with a closing tag, I did not want to prevent it from having a following indent.)
