### ISSUE TITLE
Ability to open definition of the extends

### ISSUE THREAD

**Issue by cybersonic** [jcberquist/sublimetext-cfml#7]
at the top of a component you might have something like:
```
<cfcomponent
	extends		= 'cfs.model.BaseORMDAO'
	accessors	= 'true'
	output		= 'false'>
...

</cfcomponent>
```

In the same way you can open a definition of a function it would be great to be able to open the ```cfcs.model.BaseORMDAO``` from the extended component.

Does that make sense?

**Comment by jcberquist** [comment]
This does make sense, and at least some version of this is in the works. Hopefully I will have something soon.

**Comment by jcberquist** [comment]
The latest update I pushed out addresses this by introducing per project mappings. Could you take a look?

**Comment by cybersonic** [comment]
Seems to work very very well! Excellent work sir! I love the F1 info too!

**Comment by jcberquist** [comment]
Great! 

By the way, do you have any suggestions for a better default mouse binding on a Mac? I don't use Mac primarily so I just found something that worked (<kbd>CMD</kbd>+<kbd>ALT</kbd>+<kbd>Left Click</kbd>) and wasn't used by default in ST and went with it. Does that seem ok, or do you think something else would be a better fit?

**Comment by cybersonic** [comment]
That seems fine to me? I am used to doing shift + click for other editors (IDEA I think?)

**Comment by mjhagen** [comment]
Oh wow, this feature is amazing! And indeed the F1 info is _very_ nice touch!

**Comment by jcberquist** [comment]
I took another look at the default OSX mousemap file, and unfortunately <kbd>SHIFT</kbd>+<kbd>CLICK</kbd> is used to "`// Select between selection and click location`". I also see that I have not paid attention to my own warning as <kbd>CMD</kbd>+<kbd>ALT</kbd>+<kbd>CLICK</kbd> is used with column select. I am going to have to come up with a different binding.  It looks like most of the good ones are taken. Do most Mac keyboards have <kbd>CTRL</kbd> button? If so, I could change it to <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>CLICK</kbd> or <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>CLICK</kbd>.

**Comment by mjhagen** [comment]
All Mac keyboards have a ctrl key and it isn't used much, so should be relatively safe to map something on.

**Comment by jcberquist** [comment]
Thanks! I will move it to <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>CLICK</kbd> for now. (<kbd>CTRL</kbd>+<kbd>CLICK</kbd> is already bound to opening the context menu.)
