### ISSUE TITLE
Color-coded formatting lost when using '\#' in <cfquery>

### ISSUE THREAD

**Issue by mrlife** [jcberquist/sublimetext-cfml#70]
When using the following code in a .cfm file, the color formatting gets confused by the use of '\#' within the SQL statement and doesn't match it to the second one.

```
<cfquery>
	BULK INSERT VAR1 FROM 'C:\#path#'
	WITH (
		FIRSTROW=2,
		BATCHSIZE=500000,
		FIELDTERMINATOR='\t'
	);
</cfquery>
```

**Comment by jcberquist** [comment]
Thanks, it looks like the SQL syntax sees the `\` as marking an escaped character, so it matches `\#` before the CFML syntax can match the `#`. I think I should be able to do something about this.
