### ISSUE TITLE
error parsing lexer?

### ISSUE THREAD

**Issue by dogsoldier68** [jcberquist/sublimetext-cfml#71]
I get this error in console when loading sublimetext 3 build 3114

error parsing lexer: Packages/CFML/syntaxes/cfml.sublime-syntax: expected match or include at line 334 column 13
generating syntax summary

(I renamed the dir to CFML as suggested)

**Comment by jcberquist** [comment]
Sorry about this. Starting in v0.21 of this plugin I make use of a feature in `.sublime-syntax` that was added in build 3116. So in order to avoid the error, you will either need to go back to v0.20 or update to 3126.

**Comment by dogsoldier68** [comment]
Thanks, that worked 3126!
