### ISSUE TITLE
neon green popup background

### ISSUE THREAD

**Issue by tomchiverton** [jcberquist/sublimetext-cfml#75]
With the monokai theme, the popup inline help box is on a neon green background. hardly easy on the eyes.
![ouch](https://cloud.githubusercontent.com/assets/684204/26051850/62c0a9d8-395b-11e7-8cf4-dd1cb29389a2.png)

**Comment by jcberquist** [comment]
Well, that certainly isn't intentional :D I can't reproduce this on either build 3126 or 3131 of Sublime Text. Which build are you using? After the CFML package updated, did you try exiting ST and restarting?

**Comment by tomchiverton** [comment]
after a restart the neon is restricted to a bar down the left side
![status5](https://cloud.githubusercontent.com/assets/684204/26095615/1fee2610-3a16-11e7-9966-f3081306dd81.png)

**Comment by jcberquist** [comment]
That looks as expected now. If you don't like it, you can always turn the adaptive styles off - and I am happy to take suggestions on improving the color palette.
