### ISSUE TITLE
Param types from cfdocs

### ISSUE THREAD

**Issue by KamasamaK** [jcberquist/sublimetext-cfml#77]
The param list from cfdocs does not display the `type`. I know that the web version doesn't either, but that's a separate issue as the data is there. 

This is to ask what people think is the preferred way to display it with the plugin. I have modified the plugin locally to simply display as `[param name]:[param type]` but maybe people would prefer it be right-aligned on that line or with some other styling/positioning.

**Comment by jcberquist** [comment]
I take it you are referring to the popup docs for functions and tags that comes from cfdocs.org data? I am happy to add the type to the docs (as you have done locally). Unfortunately as far as I know the Minihtml engine in ST doesn't support right alignment so the way you added locally sounds good to me.

**Comment by KamasamaK** [comment]
Yes, the overlay is what I am referring to. I wasn't aware that there were such restrictions with alignment. I just did it that way to be simple and consistent with the return type.
