### ISSUE TITLE
User Key Bindings

### ISSUE THREAD

**Issue by timsayshey** [jcberquist/sublimetext-cfml#8]
First off, thank you! This plugin is awesome and a huge step forward :+1: 

In regards to key bindings, I noticed that other plugins let you set user and default key bindings but didn't see the option.

See screenshot:
![screenshot at jan 29 16-27-52](https://cloud.githubusercontent.com/assets/1148940/12689916/74b21d7c-c6a5-11e5-92d2-d9058128993a.png)

Thanks!

**Comment by jcberquist** [comment]
Thanks! I am glad you find the plugin useful.

Regarding the user key bindings, I would have thought that one would be inclined just to edit their global user key bindings file? (In your screenshot that would be `Key Bindings - User` in the preferences menu.) Do other packages typically offer a package specific user key bindings file?

Either way I can see that it would be useful to have easy access to the default key bindings file for the package, so you can see what to override.

**Comment by jcberquist** [comment]
I have looked around a little more, and it looks like you can't name a key bindings file anything other than `Default` or `Default (platform)`. So any links to user key bindings from different packages are always going to be to the same global user key bindings file. That said, I do see other packages provide a link to user key bindings, so I am happy to as well.

**Comment by timsayshey** [comment]
This is working great, thanks!
