### ISSUE TITLE
Can you make cfinput not indent the next line?

### ISSUE THREAD

**Issue by WebVeteran** [jcberquist/sublimetext-cfml#82]
I tried to work that out with preferences, but did not see a way how to.

**Comment by jcberquist** [comment]
The file that controls indenting after cfml tags is `cfml-indent.tmPreferences` -
 see, in particular, [L38-L42](https://github.com/jcberquist/sublimetext-cfml/blob/master/metadata/cfml-indent.tmPreferences#L38-L42) and [L57-L60](https://github.com/jcberquist/sublimetext-cfml/blob/master/metadata/cfml-indent.tmPreferences#L57-L60). As you can see, `cfinput` is missing from those lists. I will get that added and pushed out in a release. In the meantime, you can create a copy of that file in your User package folder and add `cfinput` to those lists.

**Comment by WebVeteran** [comment]
Hi John, I tried doing that before making the above request - I would have made a fork and pull request.
But when I restarted sublime after my attempt, cfml was broken entirely. I figured I was missing something elsewhere, and it was beyond my knowledge.

**Comment by jcberquist** [comment]
I am sorry to hear that. Can you tell me how you installed this package? Did you use Package Control, or did you install it manually?

In any case, I was able to test my suggestion and it appears it won't work, sorry for the bad advice. The `cfml-indent.tmPreferences` file has to be overwritten completely. If you installed this package via PC, you could use the `PackageResourceViewer` package to extract this file and then any edits you make to it would overwrite the source file in the package. Or if you installed it manually you could edit the file in place. Neither option is ideal, but I am going to push an update out that includes cfinput so it should stop being an issue shortly.

**Comment by WebVeteran** [comment]
I'm pretty sure it was through PackageControl.
As for making changes... I'm not familiar with how it works. But I can continue to report issues as I find them.
