### ISSUE TITLE
Unindent automatically after closing CFML tag

### ISSUE THREAD

**Issue by WebVeteran** [jcberquist/sublimetext-cfml#83]
After a `<cfif>` the next link get indented automatically. But the closing `</cfif>` does not auto unindent. I'm not sure if this is an oversight in ST3 or your extension. But I can't find a config setting anywhere to control this functionality. All paired tags should unindent when closing.

**Comment by jcberquist** [comment]
Could you give me a specific example so I can replicate the behavior you are seeing?

**Comment by WebVeteran** [comment]
See attached mov (in zip) to see what I mean. Coda2 automatically unindents the `</cfif>` whereas Sublime3 does not.

[unindent.mov.zip](https://github.com/jcberquist/sublimetext-cfml/files/1271337/unindent.mov.zip)

**Comment by WebVeteran** [comment]
I'll make it easier...
![unindent](https://user-images.githubusercontent.com/40175/29985404-de3210ee-8f2c-11e7-9c67-afe8ae4dcd5d.gif)

**Comment by jcberquist** [comment]
Thanks! For this particular sort of case at least, I think I can improve things.

**Comment by WebVeteran** [comment]
This seems to be working perfectly now. I had two "cfml" packages in ST3. After deleting both and reinstalling yours again, all fixed!

I'd like to discuss two unrelated things with you. Please email me: jules [at] webveteran [dot] com

**Comment by jcberquist** [comment]
Good to hear it is working now. Could you say more about what you want to discuss?

**Comment by WebVeteran** [comment]
1) If you have any intent on porting this to Visual Studio Code. I think what you've done with this extension in ST3 is much better than cfml extensions for VSC. However I find VSC a much better editor/ide than ST3. I'd be willing to help a lot... I just don't know what I'm doing =) You can point out nails and I can hammer them in.

2) Are you available for coldfusion subcontracting?

**Comment by jcberquist** [comment]
Thanks for elaborating. 

To the second point, while I appreciate the question, my time is completely full 😄 .

Regarding the first - the situation is complicated. I, too, really like VSC. However, I started this package when ST introduced a new format for syntax highlighting that superseded the older TextMate derived `.tmLanguage` files. It really is a superior format and it makes it possible to highlight CFML files much more accurately than before. VSC and Atom still both rely on `.tmLanguage` syntax highlighting. I feel that the syntax highlighting is the foundation of this package, and it is not possible right now to replicate it in the other editors. 

I think, too, that the future is probably going to be found in implementing a language server for CFML (https://github.com/Microsoft/language-server-protocol). That is the approach VSC takes, and I see that Atom is heading that way as well with the just announced Atom-IDE (http://blog.atom.io/2017/09/12/announcing-atom-ide.html). Work has also been done on implementing LSP in ST as well (https://github.com/tomv564/LSP). 

So I guess to answer the first point, I don't think it is really possible to port the syntax highlighting over to VSC, and I suspect it would not be the right approach to port the other features I have in this package over to VSC, but rather to develop a language server for CFML. I would love to see that, but it is not something I can work on right now.

**Comment by WebVeteran** [comment]
Glad to hear your plate is full. Better to have more work than less.

Wow, a lot of that is over my head =)

The problem I have with Atom and SVC is that when I automcomplete 'cfinput' for example, it inserts every single parameter `<cfinput name = "" type = "[ ]" label = "[ ]" style = "[ ]" required = "[ ]" mask = "[ ]" validate = "[ ]" validateAt= "[ ]" message = "[ ]" range = "[ ]" maxlength = "[ ]" pattern = "[ ]" onValidate = "[ ]" onError = "[ ]" size = "[ ]" value = "[ ]" bind = "[ ]" checked = "[ ]" disabled = "[ ]" src = "[ ]" onKeyUp = "[ ]" onKeyDown = "[ ]" onMouseUp = "[ ]" onMouseDown = "[ ]" onChange = "[ ]" onClick = "[ ]" firstDayOfWeek = "[ ]" dayNames = "[ ]" monthNames = "[ ]" enabled = "[ ]" visible = "[ ]" toolTip = "[ ]" height = "[ ]" width = "[ ]">`
Its frustrating when I just need 1 or two. I didn't see a way of turning that off.

ST3 is nicer in that regard. But it's GUI needs a lot more... GUI.  And the FTP support is pretty bad.

My favorite is Coda2. But Panic blames OSX for their faults. Like font rendering issues. Also upload-on-save stops working after a few files. Other nuisances as well. Bah! Coder life issues! haha
