### ISSUE TITLE
html formatting / autocomplete in cfc

### ISSUE THREAD

**Issue by jimpriest** [jcberquist/sublimetext-cfml#84]
HTML autocomplete works fine when I'm in a .cfml file but doesn't work when I'm in a .cfc.

`ie I type 'h1' and then hit TAB I get <h1></h1>`

Is there a way to enable that? I've dug through all the config files but didn't see anything obvious.

**Comment by jcberquist** [comment]
If you are not using a plugin such as Emmet, than the behavior you are describing comes from the <kbd>TAB</kbd> key triggering the Sublime Text `insert_best_completion` command. If you hit tab after `h1` you get the completion from the default HTML package, which only provides completions when the cursor is in an area scoped as `text.html -source` (you can see the relevant code here: [HTML/html_completions.py#L200-L210](https://github.com/sublimehq/Packages/blob/a290aa062eb00ad5cfc6d9c454c53fb0a534a913/HTML/html_completions.py#L200-L210)) That selector means that the completions are not provided when the scope `source` is present - and it is in CFC files.

One option you have is to create a custom listener based off of that one. You could create a `.py` file in your User package folder with the following contents:
```python
from HTML.html_completions import HtmlTagCompletions

class CustomHtmlTagCompletions(HtmlTagCompletions):

    def on_query_completions(self, view, prefix, locations):
        # Only trigger within CFML
        if not view.match_selector(locations[0], "source.cfml text.html"):
            return []

        # check if we are inside a tag
        is_inside_tag = view.match_selector(locations[0],
                "text.html meta.tag - text.html punctuation.definition.tag.begin")

        return self.get_completions(view, prefix, locations, is_inside_tag)
```
This would only trigger in CFML source files, so it would not compete with the default HTML completions. Now, you should be aware that the only place currently in CFC files where the scope `text.html` is present is inside `<cffunction>` blocks in tag components. So if you are looking for those completions somewhere else in a CFC you will need to adjust the scope selector. But be aware that HTML is still only going to be highlighted as such inside of `<cffunction>` blocks.

**Comment by jcberquist** [comment]
@jimpriest I would like to close this issue - if you have further questions please let me know.
