### ISSUE TITLE
Syntax highlighting errors for custom tag names

### ISSUE THREAD

**Issue by gt-kahootz** [jcberquist/sublimetext-cfml#87]
Hi, 

We have custom tags with underscores in the name: eg. `<cf_com_utl_validateParams ....>`

The CFML package in Sublime 3 highlights the name part from the 2nd underscore onwards in pink (so in the above example, `_utl_validateParams` is highlighted), presumably as part of a syntax check?

Can we turn that off?

Thanks.

**Comment by redtopia** [comment]
Similar issue... custom tags with hyphens, so highlighting <cf_custom-tag /> breaks at the hyphen.

**Comment by jcberquist** [comment]
Thanks for the reports. I should have a fix for this out shortly.

**Comment by gt-kahootz** [comment]
Fixed!  Thanks John!
