### ISSUE TITLE
Ternary operator breaks syntax colouring

### ISSUE THREAD

**Issue by gt-kahootz** [jcberquist/sublimetext-cfml#88]
When using the ternery operator `<test> ? <if-true> : <if-false>`, the syntax colouring breaks - the next immediate CF tag is not coloured correctly, but the one after is.  This is also the case for the elvis operator `?:`

So in the following example:
```
<cfset bob = (option eq 1) ? 'hello' : 'world'>
<cfoutput>#bob#</cfoutput>
```
The `<cfoutput>` is not coloured as a valid CF tag, but the closing `</cfoutput>` is.

If I wrap the _entire_ ternary in parens then the syntax colouring is OK, but I shouldn't have to do that.

**Comment by jcberquist** [comment]
Sorry about this. I am bouncing back and forth between this sort of issue and #86 - I think a more complete solution will be necessary. It should be fixable though.

**Comment by gt-kahootz** [comment]
Thanks for the quick fix, John!
