### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by MariannaAtPlay** [jcberquist/sublimetext-cfml#90]
Hello!

I just installed a fresh version of Sublime Text 3 (windows 64 bit) and your package through Package Control.

I am getting this error message when I open a project that was previously created with Sublime Text 2 (which I still have installed on my system):
![image](https://user-images.githubusercontent.com/24710247/31182359-a8325bdc-a8f1-11e7-9a49-0e4df16f8eb5.png)

As a result, there is no syntax highlighting at all.

Any ideas about how to fix this?

Thank you!

**Comment by jcberquist** [comment]
I assume the error is coming in your copy of ST3 and not ST2? And you are opening a project you had in ST2? If that is the case, could you try closing either closing the view with no syntax highlighting and reopening it, or selecting `CFML` from the language list (use the command palette and find `Set Syntax: CFML`)? I know that in ST3, once a view is opened, ST retains which syntax highlighting file it is using (and this persists across restarts so long as the view stays open). I am just guessing, but perhaps if that view had been opened in ST2 and was using the SublimeText/ColdFusion package, and then you opened the project in ST3 without ever closing that file, that it retained the name of the syntax file it had been using in ST2. I don't have ST2 installed currently, so I may be way off base here.

**Comment by MariannaAtPlay** [comment]
This worked! That was a simple solution I would never think of! Who could've thought that closing and opening a file would be more effective than a re-start! :)

Thank you so much, John! I felt so frustrated after spending a lot of time setting up my new ST3 environment and not getting things to function....

Looking forward to trying out your package.

Marianna

**Comment by jcberquist** [comment]
Glad it is sorted out 😄  It is nice when things have a simple solution!
