### ISSUE TITLE
Custom Coloring for CFML Tags

### ISSUE THREAD

**Issue by MariannaAtPlay** [jcberquist/sublimetext-cfml#91]
Hi John,

I am trying to enable the Custom Coloring for CFML Tags. I followed the instructions, (CFML: Toggle Color Scheme Styles) but am not seeing any difference? I tried closing and opening the files as well as restarting ST.

My current color  scheme is "Packages/Color Scheme - Default/Solarized (Light).tmTheme"

Any thoughts?

Thanks!

**Comment by jcberquist** [comment]
In the latest builds, the older color schemes have been moved from the `Color Scheme - Default` package to a `Color Scheme - Legacy` package. I see that setting the color scheme to `Packages/Color Scheme - Default/Solarized (Light).tmTheme` still works, but I think ST must be performing some mapping behind the scenes. The new path to the color scheme is `Packages/Color Scheme - Legacy/Solarized (Light).tmTheme`. If you set  your color scheme to that in your settings, then things should work.

Incidentally if you add `"show_legacy_color_schemes": true` to your settings, then those older color schemes will show up in the color scheme picker again.

**Comment by MariannaAtPlay** [comment]
Awesome, this worked! Although the color difference is very slight, but it's there! Where would I customize the color of the CF tags?

Thanks for the second tip too! I was wondering why I am seeing so few options when I go to the Color Scheme menu... I don't like the new ones at all! :)

Thank you for your help!

**Comment by jcberquist** [comment]
If you go to the CFML package settings (which you can get to from the command palatte - search for `CFML: Settings` - or you can go to `Preferences -> Package Settings -> CFML -> Settings` in the menu), then the settings you are looking for are the following:
```
"cfml_tag_style": { "foreground": "#4C9BB0", "fontStyle": "" },
"cfml_tag_attribute_style": { "foreground": "#D9995E", "fontStyle": "" }
```
You would add those to your CFML package user settings, and then you can set the colors yourself. After you have added those settings you will need to run `CFML: Toggle Color Scheme Styles` twice to remove the custom styles and then re-add with the new settings.
