### ISSUE TITLE
Add support for super keyword

### ISSUE THREAD

**Issue by mjhagen** [jcberquist/sublimetext-cfml#93]
Would it be possible to have function auto complete/insight for functions residing in the parent component(s)?

So have this auto-complete:
```
super.myFunc();
```

When the component mentioned in `extends` is available.

**Comment by jcberquist** [comment]
@mjhagen: If I understand you, this should be working already. The limitation is that the parent component has to have been indexed. Perhaps in your case it wasn't?

**Comment by mjhagen** [comment]
Oh, it is? It wasn't for a cfc that had other insight working. Let me double check.

Aah! Right you are :) The super cfc was found using `f1` I guess through the defined `mappings`, but it wasn't indexed using the `cfc_folders` setting.

Thanks! (Closing this now.)
