### ISSUE TITLE
no such target scope:source.css#rule-list-body

### ISSUE THREAD

**Issue by ivanionut** [jcberquist/sublimetext-cfml#96]
Hello,
today, after upgrading to the `ST DEV 3154` version, I get out the following error:

> Error loading syntax file "Packages/CFML/syntaxes/cfml.sublime-syntax": no such target scope:source.css#rule-list-body

![st](https://hostr.co/file/Abpc23V87EOl/st_cfml.png)

**Comment by jcberquist** [comment]
Have you seen this: https://forum.sublimetext.com/t/no-such-target-scope-source-css-rule-list-body-on-most-of-syntaxes-with-3154/33294/3

I would guess you have a third party CSS syntax installed?

**Comment by ivanionut** [comment]
At this point, the problem is with the CSS3 plugin. We can also close this thread.

Thank you for your help. 👋

**Comment by jcberquist** [comment]
No problem. I see an issue has been raised in the CSS3 repo, so hopefully it will get updated to fix this.
