### ISSUE TITLE
CF Tags in Script Format using : vs = in attribute settings

### ISSUE THREAD

**Issue by GiancarloGomez** [jcberquist/sublimetext-cfml#98]
I don't remember which update caused this and maybe there is a setting I can change so this does not occur. The issue I am experiencing is when I work with a cftag inside a script block, the image below should help clarify.

![screen shot 2017-11-28 at 3 45 18 pm](https://user-images.githubusercontent.com/152279/33343397-29ab8b66-d453-11e7-9549-7d3170a95dcc.png)

I know it is not a big deal but is there a way to allow the use of semicolons and avoid Sublime from marking them red?

**Comment by jcberquist** [comment]
@GiancarloGomez: yes I should be able to fix that. Thanks for bringing it up - I believe that at least on Lucee one can also pass named function arguments using the colon instead of the equals sign. Do you know of any other cases?

**Comment by GiancarloGomez** [comment]
As of now this is the only case where it occurs.
