### ISSUE TITLE
CFC Function Name Format Issue

### ISSUE THREAD

**Issue by GiancarloGomez** [jcberquist/sublimetext-cfml#99]
Hey @jcberquist, 

I was actually wrong, there is other use cases. Here is another one that started appearing a while ago. It is with the name of a function. It appears if you start the name of a function with a dollar sign then you get the format warning.

![screen shot 2017-11-30 at 12 09 48 pm](https://user-images.githubusercontent.com/152279/33444224-af02ec76-d5c7-11e7-8438-57cfb37705bf.png)

**Comment by GiancarloGomez** [comment]
Thank you sir!

**Comment by jcberquist** [comment]
No problem - thanks for bringing it up!
